/**
 * bridge-constants.ts
 * Valores exactos aceptados por la API de Bridge (https://apidocs.bridge.xyz)
 * Usar siempre estos valores en los formularios de KYC/KYB — nunca texto libre.
 */

// ─── Tipos de documento de identificación aceptados por Bridge ───────────────
export const INDIVIDUAL_ID_TYPES = [
  { value: 'passport',               label: 'Pasaporte' },
  { value: 'national_id',            label: 'Cédula de Identidad / DNI' },
  { value: 'drivers_license',        label: 'Licencia de Conducir' },
  { value: 'permanent_residency_id', label: 'Residencia Permanente' },
  { value: 'state_or_provincial_id', label: 'ID Estatal o Provincial' },
  { value: 'military_id',            label: 'ID Militar' },
  { value: 'visa',                   label: 'Visa' },
] as const

export type IndividualIdType = typeof INDIVIDUAL_ID_TYPES[number]['value']

// ─── Tipo de identificación fiscal (para UBOs y empresas) ───────────────────
export const TAX_ID_TYPES = [
  { value: 'ssn',   label: 'SSN (EE.UU.)' },
  { value: 'ein',   label: 'EIN (EE.UU. - Empresa)' },
  { value: 'tin',   label: 'TIN (Número de Identificación Tributaria)' },
  { value: 'nit',   label: 'NIT (Bolivia)' },
  { value: 'cpf',   label: 'CPF (Brasil)' },
  { value: 'cnpj',  label: 'CNPJ (Brasil - Empresa)' },
  { value: 'ruc',   label: 'RUC' },
  { value: 'cc',    label: 'Cédula de Ciudadanía' },
  { value: 'curp',  label: 'CURP (México)' },
  { value: 'rfc',   label: 'RFC (México)' },
  { value: 'other', label: 'Otro' },
] as const

// ─── Source of funds — Individual ─────────────────────────────────────────────
// IMPORTANTE: Valores alineados con Bridge API enum (actualizado según OpenAPI spec)
export const INDIVIDUAL_SOURCE_OF_FUNDS = [
  { value: 'salary',                      label: 'Salario / Nómina' },
  { value: 'savings',                     label: 'Ahorros' },
  { value: 'company_funds',               label: 'Fondos empresariales' },
  { value: 'investments_loans',           label: 'Inversiones / Préstamos' },
  { value: 'government_benefits',         label: 'Beneficios gubernamentales' },
  { value: 'pension_retirement',          label: 'Pensión / Jubilación' },
  { value: 'inheritance',                 label: 'Herencia' },
  { value: 'gifts',                       label: 'Donación / Regalo' },
  { value: 'sale_of_assets_real_estate',  label: 'Venta de activos / inmuebles' },
  { value: 'ecommerce_reseller',          label: 'Revendedor / E-commerce' },
  { value: 'someone_elses_funds',         label: 'Fondos de terceros' },
  { value: 'gambling_proceeds',           label: 'Ingresos de juegos de azar' },
] as const

export type IndividualSourceOfFunds = typeof INDIVIDUAL_SOURCE_OF_FUNDS[number]['value']

// ─── Account purpose — Individual ─────────────────────────────────────────────
// IMPORTANTE: Valores alineados con Bridge API enum (actualizado según OpenAPI spec)
export const INDIVIDUAL_ACCOUNT_PURPOSE = [
  { value: 'payments_to_friends_or_family_abroad', label: 'Pagos a familia / amigos en el extranjero' },
  { value: 'personal_or_living_expenses',          label: 'Gastos personales / de vida' },
  { value: 'receive_salary',                       label: 'Recibir salario' },
  { value: 'purchase_goods_and_services',          label: 'Compra de bienes y servicios' },
  { value: 'receive_payment_for_freelancing',      label: 'Cobros por trabajo freelance' },
  { value: 'investment_purposes',                  label: 'Inversiones' },
  { value: 'operating_a_company',                  label: 'Operación de una empresa' },
  { value: 'ecommerce_retail_payments',            label: 'Pagos e-commerce / retail' },
  { value: 'charitable_donations',                 label: 'Donaciones benéficas' },
  { value: 'protect_wealth',                       label: 'Protección de patrimonio' },
  { value: 'other',                                label: 'Otro' },
] as const

export type IndividualAccountPurpose = typeof INDIVIDUAL_ACCOUNT_PURPOSE[number]['value']

// ─── Expected monthly payments — Individual & Business ───────────────────────
// Valores exactos del enum Bridge según OpenAPI spec (actualizados)
export const EXPECTED_MONTHLY_PAYMENTS = [
  { value: '0_4999',      label: 'Menos de $5,000 USD/mes' },
  { value: '5000_9999',   label: '$5,000 – $9,999 USD/mes' },
  { value: '10000_49999', label: '$10,000 – $49,999 USD/mes' },
  { value: '50000_plus',  label: '$50,000+ USD/mes' },
] as const

export type ExpectedMonthlyPayments = typeof EXPECTED_MONTHLY_PAYMENTS[number]['value']

// ─── Estimated annual revenue — Business (P1 high-risk) ──────────────────────
// Valores exactos del enum Bridge OpenAPI spec
export const ANNUAL_REVENUE_RANGES = [
  { value: '0_99999',             label: 'Menos de $100,000 USD/año' },
  { value: '100000_999999',       label: '$100,000 – $999,999 USD/año' },
  { value: '1000000_9999999',     label: '$1M – $9.9M USD/año' },
  { value: '10000000_49999999',   label: '$10M – $49.9M USD/año' },
  { value: '50000000_249999999',  label: '$50M – $249M USD/año' },
  { value: '250000000_plus',      label: '$250M+ USD/año' },
] as const

export type AnnualRevenueRange = typeof ANNUAL_REVENUE_RANGES[number]['value']

// ─── Employment status — Individual (P1 high-risk) ────────────────────────────
// Valores exactos Bridge API OpenAPI spec (agregado: homemaker; removido: other)
export const EMPLOYMENT_STATUS_OPTIONS = [
  { value: 'employed',      label: 'Empleado (relación de dependencia)' },
  { value: 'self_employed', label: 'Independiente / Autónomo' },
  { value: 'unemployed',    label: 'Desempleado' },
  { value: 'student',       label: 'Estudiante' },
  { value: 'retired',       label: 'Jubilado / Retirado' },
  { value: 'homemaker',     label: 'Amo/a de casa' },
] as const

export type EmploymentStatus = typeof EMPLOYMENT_STATUS_OPTIONS[number]['value']

// ─── Most Recent Occupation — Individual (required for restricted countries/high-risk) ──
// Códigos O*NET-SOC exactos aceptados por Bridge API
// Ref: https://apidocs.bridge.xyz/platform/customers/compliance/sof-eu-most-recent-occupation-list
// IMPORTANTE: estos son los únicos códigos válidos — no usar valores inventados
export const OCCUPATION_OPTIONS = [
  // Gerencia y Dirección
  { value: '111011', label: 'Chief Executives / Ejecutivos y Directores Generales' },
  { value: '111021', label: 'General and Operations Managers / Gerentes de Operaciones' },
  { value: '112011', label: 'Advertising and Promotions Managers / Gerentes de Publicidad' },
  { value: '112021', label: 'Marketing Managers / Gerentes de Marketing' },
  { value: '112022', label: 'Sales Managers / Gerentes de Ventas' },
  { value: '112030', label: 'Public Relations Managers / Gerentes de Relaciones Públicas' },
  { value: '113011', label: 'Administrative Services Managers / Gerentes Administrativos' },
  { value: '113021', label: 'Computer and IT Managers / Gerentes de Sistemas' },
  { value: '113031', label: 'Financial Managers / Gerentes Financieros' },
  { value: '113051', label: 'Industrial Production Managers / Gerentes de Producción' },
  { value: '113061', label: 'Purchasing Managers / Gerentes de Compras' },
  { value: '113071', label: 'Transportation Managers / Gerentes de Transporte' },
  { value: '119041', label: 'Compliance Managers / Gerentes de Cumplimiento Regulatorio' },
  // Finanzas y Negocios
  { value: '131011', label: 'Agents and Business Managers / Agentes y Representantes' },
  { value: '131021', label: 'Buyers and Purchasing Agents / Agentes de Compras' },
  { value: '131030', label: 'Claims Adjusters / Ajustadores de Seguros' },
  { value: '131041', label: 'Compliance Officers / Oficiales de Cumplimiento' },
  { value: '131051', label: 'Cost Estimators / Estimadores de Costos' },
  { value: '131070', label: 'Human Resources Workers / Recursos Humanos' },
  { value: '131081', label: 'Logisticians / Logísticos' },
  { value: '132011', label: 'Accountants and Auditors / Contadores y Auditores' },
  { value: '132020', label: 'Appraisers and Assessors / Evaluadores y Tasadores' },
  { value: '132031', label: 'Budget Analysts / Analistas de Presupuesto' },
  { value: '132041', label: 'Credit Analysts / Analistas de Crédito' },
  { value: '132051', label: 'Financial Analysts / Analistas Financieros' },
  { value: '132061', label: 'Financial Examiners / Revisores Financieros' },
  { value: '132070', label: 'Financial Risk Specialists / Especialistas en Riesgo' },
  { value: '132081', label: 'Tax Examiners / Inspectores Fiscales' },
  { value: '132082', label: 'Tax Preparers / Preparadores de Impuestos' },
  // Ciencias e Ingeniería
  { value: '151221', label: 'Computer and IS Research Scientists / Investigadores en Sistemas' },
  { value: '151241', label: 'Computer Network Architects / Arquitectos de Redes' },
  { value: '151244', label: 'Network and Systems Administrators / Administradores de Redes' },
  { value: '151251', label: 'Computer Programmers / Programadores' },
  { value: '151252', label: 'Software Developers / Desarrolladores de Software' },
  { value: '151253', label: 'Software Quality Assurance Analysts / QA Analistas' },
  { value: '151255', label: 'Web and Digital Interface Designers / Diseñadores Web' },
  { value: '152011', label: 'Actuaries / Actuarios' },
  { value: '152021', label: 'Mathematicians / Matemáticos' },
  { value: '152031', label: 'Operations Research Analysts / Analistas de Operaciones' },
  { value: '152041', label: 'Statisticians / Estadísticos' },
  { value: '172011', label: 'Aerospace Engineers / Ingenieros Aeroespaciales' },
  { value: '172021', label: 'Agricultural Engineers / Ingenieros Agrícolas' },
  { value: '172031', label: 'Bioengineers / Bioingenieros' },
  { value: '172041', label: 'Chemical Engineers / Ingenieros Químicos' },
  { value: '172051', label: 'Civil Engineers / Ingenieros Civiles' },
  { value: '172061', label: 'Computer Hardware Engineers / Ingenieros de Hardware' },
  { value: '172070', label: 'Electrical Engineers / Ingenieros Eléctricos' },
  { value: '172081', label: 'Environmental Engineers / Ingenieros Ambientales' },
  { value: '172110', label: 'Industrial Engineers / Ingenieros Industriales' },
  { value: '172121', label: 'Marine Engineers / Ingenieros Navales' },
  { value: '172131', label: 'Materials Engineers / Ingenieros de Materiales' },
  { value: '172141', label: 'Mechanical Engineers / Ingenieros Mecánicos' },
  { value: '172151', label: 'Mining and Geological Engineers / Ingenieros de Minería' },
  { value: '172161', label: 'Nuclear Engineers / Ingenieros Nucleares' },
  { value: '172171', label: 'Petroleum Engineers / Ingenieros Petroleros' },
  // Salud
  { value: '211011', label: 'Substance Abuse Counselors / Consejeros de Adicciones' },
  { value: '291011', label: 'Chiropractors / Quiroprácticos' },
  { value: '291020', label: 'Dentists / Dentistas' },
  { value: '291031', label: 'Dietitians and Nutritionists / Nutricionistas' },
  { value: '291041', label: 'Optometrists / Optometristas' },
  { value: '291051', label: 'Pharmacists / Farmacéuticos' },
  { value: '291071', label: 'Physician Assistants / Asistentes Médicos' },
  { value: '291081', label: 'Podiatrists / Podólogos' },
  { value: '291122', label: 'Occupational Therapists / Terapistas Ocupacionales' },
  { value: '291123', label: 'Physical Therapists / Fisioterapeutas' },
  { value: '291124', label: 'Radiation Therapists / Radioterapeutas' },
  { value: '291125', label: 'Recreational Therapists / Terapistas Recreativos' },
  { value: '291126', label: 'Respiratory Therapists / Terapistas Respiratorios' },
  { value: '291127', label: 'Speech Pathologists / Patólogos del Habla' },
  { value: '291128', label: 'Exercise Physiologists / Fisiólogos del Ejercicio' },
  { value: '291129', label: 'Physical Medicine Physicians / Médicos de Rehabilitación' },
  { value: '291131', label: 'Veterinarians / Veterinarios' },
  { value: '291141', label: 'Registered Nurses / Enfermeros Registrados' },
  { value: '291151', label: 'Nurse Anesthetists / Enfermeros Anestesiólogos' },
  { value: '291161', label: 'Nurse Midwives / Enfermeras Parteras' },
  { value: '291171', label: 'Nurse Practitioners / Enfermeros Profesionales' },
  { value: '291181', label: 'Audiologists / Audiólogos' },
  { value: '291214', label: 'Emergency Physicians / Médicos de Emergencias' },
  { value: '291224', label: 'Radiologists / Radiólogos' },
  { value: '291240', label: 'General Physicians / Médicos Generales' },
  { value: '291291', label: 'Healthcare Practitioners, All Other / Otro Profesional de Salud' },
  // Educación
  { value: '251000', label: 'Postsecondary Teachers / Profesores Universitarios' },
  { value: '252010', label: 'Preschool and Kindergarten Teachers / Maestros Preescolares' },
  { value: '252020', label: 'Elementary School Teachers / Maestros de Primaria' },
  { value: '252030', label: 'Secondary School Teachers / Maestros de Secundaria' },
  { value: '252050', label: 'Special Education Teachers / Maestros de Educación Especial' },
  { value: '253041', label: 'Adult Literacy Instructors / Instructores de Alfabetización' },
  { value: '254010', label: 'Archivists and Curators / Archivistas y Curadores' },
  { value: '254022', label: 'Librarians / Bibliotecarios' },
  { value: '254031', label: 'Library Technicians / Técnicos de Biblioteca' },
  // Legal
  { value: '231011', label: 'Lawyers / Abogados' },
  { value: '231012', label: 'Judicial Law Clerks / Asistentes Judiciales' },
  { value: '231020', label: 'Paralegals and Legal Assistants / Paralegales' },
  { value: '232011', label: 'Court Reporters / Taquígrafos Judiciales' },
  { value: '232093', label: 'Title Examiners / Examinadores de Títulos' },
  { value: '232099', label: 'Legal Support Workers / Trabajadores de Apoyo Legal' },
  // Arte, Diseño y Media
  { value: '271010', label: 'Art Directors / Directores de Arte' },
  { value: '271021', label: 'Commercial / Graphic Designers / Diseñadores Gráficos' },
  { value: '271022', label: 'Fashion Designers / Diseñadores de Moda' },
  { value: '271023', label: 'Floral Designers / Diseñadores Florales' },
  { value: '271024', label: 'Industrial Designers / Diseñadores Industriales' },
  { value: '271025', label: 'Interior Designers / Diseñadores de Interiores' },
  { value: '271026', label: 'Merchandise Displayers / Vitrinistas' },
  { value: '272011', label: 'Actors / Actores' },
  { value: '272012', label: 'Producers and Directors / Productores y Directores' },
  { value: '272021', label: 'Athletes and Sports Coaches / Atletas y Entrenadores' },
  { value: '272022', label: 'Coaches and Scouts / Entrenadores Deportivos' },
  { value: '272023', label: 'Umpires and Referees / Árbitros' },
  { value: '272030', label: 'Dancers and Choreographers / Bailarines y Coreógrafos' },
  { value: '272041', label: 'Music Directors and Composers / Directores Musicales' },
  { value: '272042', label: 'Musicians and Singers / Músicos y Cantantes' },
  { value: '272091', label: 'Entertainers and Performers / Artistas y Entretenedores' },
  { value: '272099', label: 'Entertainers, All Other / Otro Artista' },
  { value: '273011', label: 'Radio and Television Announcers / Locutores de Radio y TV' },
  { value: '273023', label: 'News Analysts / Analistas de Noticias' },
  { value: '273031', label: 'Public Relations Specialists / Especialistas en RR.PP.' },
  { value: '273041', label: 'Editors / Editores' },
  { value: '273042', label: 'Technical Writers / Escritores Técnicos' },
  { value: '273043', label: 'Web Content Writers / Escritores de Contenido Web' },
  { value: '273091', label: 'Interpreters and Translators / Intérpretes y Traductores' },
  { value: '273092', label: 'Court Interpreters / Intérpretes Judiciales' },
  { value: '273099', label: 'Media and Communication Workers, All Other / Otro Comunicador' },
  { value: '274010', label: 'Broadcast Technicians / Técnicos de Transmisión' },
  { value: '274021', label: 'Sound Engineering Technicians / Técnicos de Sonido' },
  { value: '274030', label: 'Camera Operators / Camarógrafos' },
  { value: '274099', label: 'Media Equipment Workers / Técnicos de Media' },
  // Ventas y Atención al Cliente
  { value: '411011', label: 'First-Line Sales Supervisors / Supervisores de Ventas' },
  { value: '411012', label: 'Sales Supervisors / Supervisores de Ventas al Detalle' },
  { value: '412010', label: 'Non-Retail Sales Workers / Vendedores (no minoristas)' },
  { value: '412021', label: 'Counter and Rental Clerks / Cajeros y Empleados de Renta' },
  { value: '412022', label: 'Parts Salespersons / Vendedores de Repuestos' },
  { value: '412031', label: 'Retail Salespersons / Vendedores al Detalle' },
  { value: '413011', label: 'Advertising Sales Agents / Agentes de Ventas Publicitarias' },
  { value: '413021', label: 'Insurance Sales Agents / Agentes de Seguros' },
  { value: '413031', label: 'Securities and Financial Services Sales / Agentes Financieros' },
  { value: '413041', label: 'Travel Agents / Agentes de Viajes' },
  { value: '413091', label: 'Sales Representatives, Services / Representantes de Ventas' },
  { value: '414010', label: 'Sales Reps, Wholesale/Manufacturing / Representantes Comerciales' },
  { value: '419010', label: 'Sales Engineers / Ingenieros de Ventas' },
  { value: '419020', label: 'Real Estate Brokers / Corredores de Bienes Raíces' },
  { value: '419031', label: 'Real Estate Sales Agents / Agentes Inmobiliarios' },
  { value: '419041', label: 'Telemarketers / Televendedores' },
  { value: '419091', label: 'Door-to-Door Sales Workers / Vendedores a Domicilio' },
  { value: '419099', label: 'Sales and Related Workers, All Other / Otro Vendedor' },
  // Servicios al Cliente y Oficina
  { value: '431011', label: 'First-Line Administrative Supervisors / Supervisores Administrativos' },
  { value: '432099', label: 'Communications Equipment Operators / Operadores de Comunicaciones' },
  { value: '433011', label: 'Bill and Account Collectors / Cobradores' },
  { value: '433021', label: 'Billing Clerks / Empleados de Facturación' },
  { value: '433031', label: 'Bookkeeping Clerks / Tenedores de Libros' },
  { value: '433041', label: 'Gambling Cage Workers / Cajeros de Casino' },
  { value: '433051', label: 'Payroll Clerks / Empleados de Nómina' },
  { value: '433061', label: 'Procurement Clerks / Empleados de Compras' },
  { value: '433071', label: 'Tellers / Cajeros Bancarios' },
  { value: '433099', label: 'Financial Clerks, All Other / Otro Empleado Financiero' },
  { value: '434011', label: 'Brokerage Clerks / Empleados de Corretaje' },
  { value: '434021', label: 'Correspondence Clerks / Empleados de Correspondencia' },
  { value: '434031', label: 'Court Clerks / Empleados de Juzgado' },
  { value: '434041', label: 'Credit Authorizers / Autorizadores de Crédito' },
  { value: '434051', label: 'Customer Service Representatives / Representantes de Servicio' },
  { value: '434061', label: 'Eligibility Interviewers / Entrevistadores de Elegibilidad' },
  { value: '434071', label: 'File Clerks / Archivistas' },
  { value: '434081', label: 'Hotel Desk Clerks / Recepcionistas de Hotel' },
  { value: '434111', label: 'Interviewers / Encuestadores' },
  { value: '434121', label: 'Library Assistants / Asistentes de Biblioteca' },
  { value: '434131', label: 'Loan Interviewers / Entrevistadores de Préstamos' },
  { value: '434141', label: 'New Accounts Clerks / Empleados de Cuentas Nuevas' },
  { value: '434151', label: 'Order Clerks / Empleados de Pedidos' },
  { value: '434161', label: 'Human Resources Assistants / Asistentes de RRHH' },
  { value: '434171', label: 'Receptionists / Recepcionistas' },
  { value: '434181', label: 'Reservation Clerks / Agentes de Reservas' },
  { value: '434199', label: 'Information and Record Clerks, All Other / Otro Empleado de Registro' },
  { value: '435011', label: 'Cargo and Freight Agents / Agentes de Carga' },
  { value: '435021', label: 'Couriers and Messengers / Mensajeros' },
  { value: '435031', label: 'Dispatchers / Despachadores' },
  { value: '435032', label: 'Radio Operators / Operadores de Radio' },
  { value: '435041', label: 'Meter Readers / Lectores de Medidores' },
  { value: '435051', label: 'Postal Service Clerks / Empleados Postales' },
  { value: '435061', label: 'Production Schedulers / Programadores de Producción' },
  { value: '435071', label: 'Shipping Clerks / Empleados de Envíos' },
  { value: '435111', label: 'Weighers and Checkers / Pesadores y Verificadores' },
  { value: '436011', label: 'Executive Secretaries / Secretarias Ejecutivas' },
  { value: '436012', label: 'Legal Secretaries / Secretarias Legales' },
  { value: '436013', label: 'Medical Secretaries / Secretarias Médicas' },
  { value: '436014', label: 'Secretaries, General / Secretarias Generales' },
  { value: '439021', label: 'Data Entry Keyers / Capturistas de Datos' },
  { value: '439022', label: 'Word Processors and Typists / Mecanógrafos' },
  { value: '439041', label: 'Insurance Claims Clerks / Empleados de Reclamaciones' },
  { value: '439051', label: 'Mail Clerks / Empleados de Correo' },
  { value: '439061', label: 'Office Clerks / Empleados de Oficina General' },
  { value: '439071', label: 'Office Machine Operators / Operadores de Máquinas de Oficina' },
  { value: '439081', label: 'Proofreaders / Correctores de Pruebas' },
  { value: '439111', label: 'Statistical Assistants / Asistentes Estadísticos' },
  { value: '439199', label: 'Office and Administrative Support Workers, All Other / Otro Apoyo Administrativo' },
  // Transporte y Logística
  { value: '492011', label: 'Avionics Technicians / Técnicos de Aviónica' },
  { value: '492020', label: 'Electrical/Electronics Installers / Instaladores Eléctricos' },
  { value: '492091', label: 'Electrical Power-Line Installers / Instaladores de Líneas Eléctricas' },
  { value: '492092', label: 'Telecommunications Equipment Installers / Instaladores de Telecomunicaciones' },
  { value: '492093', label: 'Telecom Line Installers / Instaladores de Líneas de Telecomunicaciones' },
  { value: '492096', label: 'Electric Meter Installers / Instaladores de Medidores Eléctricos' },
  { value: '492097', label: 'Electronic Home Entertainment Installers / Instaladores de Entretenimiento' },
  { value: '492098', label: 'Security Systems Installers / Instaladores de Seguridad' },
  { value: '493010', label: 'First-Line Repair Supervisors / Supervisores de Mantenimiento' },
  { value: '493021', label: 'Automotive Body Repairers / Hojalateros' },
  { value: '493022', label: 'Automotive Glass Installers / Instaladores de Vidrios Automotrices' },
  { value: '493023', label: 'Automotive Service Technicians / Mecánicos Automotrices' },
  { value: '493031', label: 'Bus and Truck Mechanics / Mecánicos de Autobuses y Camiones' },
  { value: '493040', label: 'Heavy Vehicle Mechanics / Mecánicos de Vehículos Pesados' },
  { value: '493050', label: 'Small Engine Mechanics / Mecánicos de Motores Pequeños' },
  { value: '499091', label: 'Coin Vending Machine Servicers / Técnicos de Máquinas Expendedoras' },
  { value: '499092', label: 'Commercial Divers / Buzos Comerciales' },
  { value: '499094', label: 'Locksmiths / Cerrajeros' },
  { value: '499095', label: 'Manufactured Building Installers / Instaladores de Edificios Prefabricados' },
  { value: '499096', label: 'Riggers / Aparejadores' },
  { value: '499098', label: 'Helpers / Ayudantes de Instalación y Reparación' },
  { value: '511011', label: 'First-Line Production Supervisors / Supervisores de Producción' },
  { value: '512011', label: 'Bakers / Panaderos' },
  { value: '512020', label: 'Butchers and Meat Cutters / Carniceros' },
  { value: '512031', label: 'Chefs and Head Cooks / Chefs y Cocineros Principales' },
  { value: '512041', label: 'Cooks / Cocineros' },
  { value: '513011', label: 'Bartenders / Bartenders' },
  { value: '513020', label: 'Fast Food Workers / Trabajadores de Comida Rápida' },
  { value: '513091', label: 'Dining Room Attendants / Ayudantes de Comedor' },
  { value: '513092', label: 'Dishwashers / Lavaplatos' },
  { value: '513093', label: 'Food Servers / Meseros' },
  { value: '513099', label: 'Food Preparation Workers, All Other / Otro Trabajador de Alimentos' },
  { value: '514031', label: 'Cooling Equipment Operators / Operadores de Equipos de Refrigeración' },
  // Construcción
  { value: '472011', label: 'Boilermakers / Caldereros' },
  { value: '472020', label: 'Bricklayers / Albañiles' },
  { value: '472031', label: 'Carpenters / Carpinteros' },
  { value: '472040', label: 'Carpet Installers / Instaladores de Alfombras' },
  { value: '472050', label: 'Ceiling Tile Installers / Instaladores de Cielos Rasos' },
  { value: '472061', label: 'Construction Laborers / Trabajadores de Construcción' },
  { value: '472070', label: 'Operating Engineers / Operadores de Equipo Pesado' },
  { value: '472080', label: 'Drywall Finishers / Instaladores de Pladur' },
  { value: '472111', label: 'Electricians / Electricistas' },
  { value: '472121', label: 'Glaziers / Vidrieros' },
  { value: '472130', label: 'Insulation Workers / Instaladores de Aislamiento' },
  { value: '472140', label: 'Painters / Pintores' },
  { value: '472151', label: 'Pipefitters / Tuberos' },
  { value: '472161', label: 'Plasterers / Enlucidores' },
  { value: '472171', label: 'Plumbers / Plomeros' },
  { value: '472181', label: 'Roofers / Techadores' },
  { value: '472211', label: 'Sheet Metal Workers / Trabajadores de Lámina' },
  { value: '472221', label: 'Structural Iron Workers / Trabajadores de Estructuras Metálicas' },
  { value: '472231', label: 'Solar Photovoltaic Installers / Instaladores Solares' },
  // Transporte
  { value: '532010', label: 'Aircraft Pilots / Pilotos de Aeronaves' },
  { value: '532020', label: 'Air Traffic Controllers / Controladores de Tráfico Aéreo' },
  { value: '532031', label: 'Flight Attendants / Auxiliares de Vuelo' },
  { value: '533011', label: 'Ambulance Drivers / Conductores de Ambulancias' },
  { value: '533030', label: 'Driver/Sales Workers / Conductores y Vendedores' },
  { value: '533051', label: 'Industrial Truck Operators / Operadores de Montacargas' },
  { value: '533052', label: 'Laborers (Moving) / Trabajadores de Mudanzas' },
  { value: '533053', label: 'Machine Feeders / Alimentadores de Máquinas' },
  { value: '533054', label: 'Packers and Packagers / Empacadores' },
  { value: '533099', label: 'Transportation Workers, All Other / Otro Trabajador de Transporte' },
  { value: '534010', label: 'Sailors and Marine Oilers / Marineros' },
  { value: '534031', label: 'Ship Engineers / Ingenieros Navales' },
  { value: '535011', label: 'Subway and Streetcar Operators / Operadores de Metro/Tranvía' },
  { value: '535020', label: 'Bus Drivers / Conductores de Autobús' },
  { value: '535031', label: 'Taxicab Drivers / Taxistas' },
  { value: '536021', label: 'Parking Attendants / Valet y Vigilantes de Estacionamiento' },
  { value: '536051', label: 'Transportation Inspectors / Inspectores de Transporte' },
  { value: '536061', label: 'Passenger Attendants / Asistentes de Pasajeros' },
  // Agricultura
  { value: '452011', label: 'Farmers, Ranchers, and Ag Managers / Agricultores y Ganaderos' },
  { value: '452021', label: 'Agricultural Inspectors / Inspectores Agrícolas' },
  { value: '452041', label: 'Graders and Sorters / Clasificadores Agrícolas' },
  { value: '452090', label: 'Agricultural Workers, All Other / Otro Trabajador Agrícola' },
  { value: '453031', label: 'Fishing and Hunting Workers / Pescadores y Cazadores' },
  { value: '454011', label: 'Forest Technicians / Técnicos Forestales' },
  { value: '454020', label: 'Fallers / Taladores' },
  // Servicios Personales y Protección
  { value: '331011', label: 'First-Line Police Supervisors / Supervisores de Policía' },
  { value: '331012', label: 'First-Line Fire Supervisors / Supervisores de Bomberos' },
  { value: '331021', label: 'Fire Inspectors / Inspectores de Incendios' },
  { value: '331091', label: 'Crossing Guards / Guardias de Cruce Escolar' },
  { value: '331099', label: 'Protective Service Workers, All Other / Otro Trabajador de Seguridad' },
  { value: '332011', label: 'Correctional Officers / Oficiales Penitenciarios' },
  { value: '332020', label: 'Detectives and Investigators / Detectives e Investigadores' },
  { value: '351011', label: 'Chefs and Head Cooks / Jefes de Cocina' },
  { value: '351012', label: 'Pastry Chefs / Pasteleros' },
  { value: '352010', label: 'Cooks / Cocineros en General' },
  { value: '352021', label: 'Fast Food Cooks / Cocineros de Comida Rápida' },
  { value: '353011', label: 'Waiters and Waitresses / Meseros' },
  { value: '353023', label: 'Counter Attendants / Empleados de Mostrador' },
  { value: '353031', label: 'Bartenders / Cantineros' },
  { value: '353041', label: 'Food Servers, Nonrestaurant / Servidores de Alimentos' },
  { value: '359011', label: 'Dining Room and Cafeteria Attendants / Ayudantes de Cafetería' },
  { value: '359021', label: 'Dishwashers / Lavaplatos' },
  { value: '359031', label: 'Hosts and Hostesses / Anfitriones de Restaurante' },
  { value: '359099', label: 'Food Preparation Workers / Trabajadores de Preparación de Alimentos' },
  { value: '371011', label: 'First-Line Housekeeping Supervisors / Supervisores de Limpieza' },
  { value: '371012', label: 'First-Line Grounds Supervisors / Supervisores de Jardinería' },
  { value: '373011', label: 'Landscapers and Groundskeepers / Jardineros' },
  { value: '373013', label: 'Tree Trimmers / Podadores de Árboles' },
  { value: '391000', label: 'Personal Care and Service Workers / Trabajadores de Servicio Personal' },
  { value: '393010', label: 'Animal Care Workers / Cuidadores de Animales' },
  { value: '393031', label: 'Fitness Trainers / Entrenadores de Fitness' },
  { value: '393091', label: 'Recreation Workers / Trabajadores de Recreación' },
  // Producción e Industria
  { value: '319011', label: 'Massage Therapists / Masajistas' },
  { value: '319091', label: 'Dental Assistants / Asistentes Dentales' },
  { value: '319092', label: 'Medical Assistants / Asistentes Médicos' },
  { value: '319094', label: 'Pharmacy Aides / Asistentes de Farmacia' },
  { value: '319095', label: 'Phlebotomists / Flebotomistas' },
  { value: '319096', label: 'Medical Transcriptionists / Transcriptores Médicos' },
  { value: '319097', label: 'Opticians / Ópticos' },
  { value: '311121', label: 'Dietetic Technicians / Técnicos en Dietética' },
  { value: '311131', label: 'Veterinary Technicians / Técnicos Veterinarios' },
  { value: '312010', label: 'Licensed Practical Nurses / Enfermeros Prácticos Licenciados' },
  { value: '312020', label: 'Medical Records Technicians / Técnicos de Registros Médicos' },
  // Otros generales
  { value: '211012', label: 'Educational Counselors / Orientadores Educativos' },
  { value: '211013', label: 'Marriage and Family Therapists / Terapistas Familiares' },
  { value: '211014', label: 'Mental Health Counselors / Consejeros de Salud Mental' },
  { value: '211015', label: 'Rehabilitation Counselors / Consejeros de Rehabilitación' },
  { value: '211019', label: 'Counselors, All Other / Consejeros, Otros' },
  { value: '211021', label: 'Child and Family Social Workers / Trabajadores Sociales' },
  { value: '211022', label: 'Healthcare Social Workers / Trabajadores Sociales de Salud' },
  { value: '211023', label: 'Mental Health Social Workers / Trabajadores Sociales de Salud Mental' },
  { value: '211029', label: 'Social Workers, All Other / Trabajadores Sociales, Otros' },
  { value: '299000', label: 'Healthcare Support, All Other / Apoyo Sanitario, Otros' },
  { value: '531000', label: 'Supervisors of Transportation / Supervisores de Transporte' },
  { value: '999999', label: 'Other / Otro' },
  { value: '999998', label: 'Not Specified / No Especificado' },
] as const

export type OccupationCode = typeof OCCUPATION_OPTIONS[number]['value']
export const OCCUPATION_VALUES = OCCUPATION_OPTIONS.map(o => o.value) as unknown as readonly [string, ...string[]]

// ─── High-risk activities — Business (P1) ────────────────────────────────────
// Valores exactos del enum Bridge OpenAPI spec
export const HIGH_RISK_ACTIVITIES = [
  { value: 'adult_entertainment',                                          label: 'Entretenimiento para adultos' },
  { value: 'gambling',                                                     label: 'Apuestas / Juegos de azar' },
  { value: 'hold_client_funds',                                            label: 'Custodia de fondos de clientes' },
  { value: 'investment_services',                                          label: 'Servicios de inversión' },
  { value: 'lending_banking',                                              label: 'Préstamos y banca' },
  { value: 'marijuana_or_related_services',                                label: 'Cannabis / Marihuana' },
  { value: 'money_services',                                               label: 'Servicios de dinero (MSB)' },
  { value: 'nicotine_tobacco_or_related_services',                         label: 'Tabaco / Nicotina' },
  { value: 'operate_foreign_exchange_virtual_currencies_brokerage_otc',    label: 'Exchange / OTC de divisas o criptomonedas' },
  { value: 'pharmaceuticals',                                              label: 'Farmacéutica / Medicamentos' },
  { value: 'precious_metals_precious_stones_jewelry',                      label: 'Metales preciosos / Joyería' },
  { value: 'safe_deposit_box_rentals',                                     label: 'Alquiler de cajas de seguridad' },
  { value: 'third_party_payment_processing',                               label: 'Procesamiento de pagos de terceros' },
  { value: 'weapons_firearms_and_explosives',                              label: 'Armas de fuego y explosivos' },
  { value: 'none_of_the_above',                                            label: 'Ninguna de las anteriores' },
] as const

export type HighRiskActivity = typeof HIGH_RISK_ACTIVITIES[number]['value']

// ─── Business industries — NAICS 2022 codes (selección resumida más relevantes) ──
// Ref: https://apidocs.bridge.xyz/platform/customers/compliance/business-industry-list-updated-2022-naics-codes
export const BUSINESS_INDUSTRIES = [
  { value: '111150',  label: 'Agricultura — Cultivo de granos' },
  { value: '212311',  label: 'Minería y Canteras' },
  { value: '221112',  label: 'Generación eléctrica (combustible fósil)' },
  { value: '221114',  label: 'Generación de energía solar' },
  { value: '311111',  label: 'Manufactura de alimentos' },
  { value: '322110',  label: 'Manufactura de papel / celulosa' },
  { value: '324110',  label: 'Refinerías de petróleo' },
  { value: '334111',  label: 'Manufactura de computadoras / electrónica' },
  { value: '334210',  label: 'Equipos de telecomunicaciones' },
  { value: '423110',  label: 'Comercio mayorista — Automotriz' },
  { value: '441110',  label: 'Concesionarios de autos' },
  { value: '444110',  label: 'Tiendas de materiales de construcción' },
  { value: '445110',  label: 'Supermercados / Grocery' },
  { value: '449110',  label: 'Muebles y mobiliario' },
  { value: '455110',  label: 'Tiendas departamentales' },
  { value: '484110',  label: 'Transporte de carga (local)' },
  { value: '484121',  label: 'Transporte de carga (larga distancia)' },
  { value: '491110',  label: 'Servicio postal / courier' },
  { value: '511210',  label: 'Editores de software' },
  { value: '517111',  label: 'Telecomunicaciones (línea fija)' },
  { value: '517112',  label: 'Telecomunicaciones (inalámbrica)' },
  { value: '518210',  label: 'Procesamiento de datos / hosting / cloud' },
  { value: '519290',  label: 'Servicios de información / portales web' },
  { value: '521110',  label: 'Banca central' },
  { value: '522110',  label: 'Banca comercial' },
  { value: '522130',  label: 'Cooperativas de ahorro y crédito' },
  { value: '522210',  label: 'Emisión de tarjetas de crédito' },
  { value: '522291',  label: 'Crédito al consumo / préstamos' },
  { value: '522320',  label: 'Procesamiento de pagos (fintech)' },
  { value: '523150',  label: 'Banca de inversión y valores' },
  { value: '523910',  label: 'Intermediación financiera' },
  { value: '523940',  label: 'Gestión de portafolio / asesoría financiera' },
  { value: '524210',  label: 'Seguros' },
  { value: '531110',  label: 'Alquiler de bienes inmuebles' },
  { value: '531210',  label: 'Corretaje de bienes inmuebles' },
  { value: '541110',  label: 'Servicios legales / abogados' },
  { value: '541211',  label: 'Contabilidad / auditoría' },
  { value: '541511',  label: 'Programación / desarrollo de software' },
  { value: '541512',  label: 'Diseño de sistemas informáticos' },
  { value: '541611',  label: 'Consultoría de negocios' },
  { value: '541613',  label: 'Consultoría de marketing' },
  { value: '541810',  label: 'Agencias de publicidad' },
  { value: '561311',  label: 'Agencias de empleo' },
  { value: '561510',  label: 'Agencias de viajes' },
  { value: '561790',  label: 'Servicios de jardinería / paisajismo' },
  { value: '611110',  label: 'Educación primaria / secundaria' },
  { value: '611310',  label: 'Educación universitaria' },
  { value: '621111',  label: 'Consultorios médicos' },
  { value: '621210',  label: 'Consultorios dentales' },
  { value: '622110',  label: 'Hospitales generales' },
  { value: '711190',  label: 'Artes escénicas / espectáculos' },
  { value: '713940',  label: 'Gimnasios y centros deportivos' },
  { value: '721110',  label: 'Hoteles y resorts' },
  { value: '722511',  label: 'Restaurantes (servicio completo)' },
  { value: '722513',  label: 'Restaurantes (rápido)' },
  { value: '811111',  label: 'Reparación automotriz general' },
  { value: '812111',  label: 'Peluquerías / barberías' },
  { value: '812210',  label: 'Funerarias / servicios fúnebres' },
  { value: '812310',  label: 'Lavanderías / tintorerías' },
  { value: '813110',  label: 'Organizaciones religiosas' },
  { value: '813211',  label: 'ONGs / fundaciones caritativas' },
  { value: '926110',  label: 'Administración pública / programas económicos' },
] as const

export type BusinessIndustryCode = typeof BUSINESS_INDUSTRIES[number]['value']
export const BUSINESS_INDUSTRY_VALUES = BUSINESS_INDUSTRIES.map(i => i.value) as unknown as readonly [string, ...string[]]

// ─── Business types ───────────────────────────────────────────────────────────
export const BUSINESS_TYPES = [
  { value: 'corporation', label: 'Sociedad Anónima (S.A. / Corporation)' },
  { value: 'llc',         label: 'Sociedad de Responsabilidad Limitada (S.R.L. / LLC)' },
  { value: 'partnership', label: 'Sociedad Colectiva / Partnership' },
  { value: 'sole_prop',   label: 'Empresa Unipersonal / Sole Proprietorship' },
  { value: 'cooperative', label: 'Cooperativa' },
  { value: 'trust',       label: 'Fideicomiso / Trust' },
  { value: 'other',       label: 'Otro' },
] as const

export type BusinessType = typeof BUSINESS_TYPES[number]['value']

// ─── Source of funds — Business ───────────────────────────────────────────────
export const BUSINESS_SOURCE_OF_FUNDS = [
  { value: 'sales_of_goods_and_services', label: 'Ventas de bienes y servicios' },
  { value: 'owners_capital',             label: 'Capital de los socios' },
  { value: 'investment_proceeds',        label: 'Rendimientos de inversiones' },
  { value: 'business_loans',            label: 'Préstamos empresariales' },
  { value: 'grants',                    label: 'Subvenciones / Donaciones' },
  { value: 'inter_company_funds',       label: 'Fondos intercompañía' },
  { value: 'sale_of_assets',            label: 'Venta de activos' },
  { value: 'treasury_reserves',         label: 'Reservas de tesorería' },
  { value: 'legal_settlement',          label: 'Acuerdo legal' },
  { value: 'pension_retirement',        label: 'Pensión / Fondo de retiro' },
  { value: 'third_party_funds',         label: 'Fondos de terceros' },
] as const

export type BusinessSourceOfFunds = typeof BUSINESS_SOURCE_OF_FUNDS[number]['value']

// ─── Account purpose — Business ───────────────────────────────────────────────
export const BUSINESS_ACCOUNT_PURPOSE = [
  { value: 'purchase_goods_and_services',             label: 'Compra de bienes y servicios' },
  { value: 'receive_payments_for_goods_and_services', label: 'Cobros por bienes/servicios' },
  { value: 'payroll',                                 label: 'Pago de nómina' },
  { value: 'treasury_management',                    label: 'Gestión de tesorería' },
  { value: 'investment_purposes',                    label: 'Inversiones' },
  { value: 'payments_to_friends_or_family_abroad',   label: 'Pagos internacionales' },
  { value: 'protect_wealth',                         label: 'Protección de patrimonio' },
  { value: 'ecommerce_retail_payments',              label: 'Pagos e-commerce / retail' },
  { value: 'charitable_donations',                   label: 'Donaciones benéficas' },
  // FIX D-02: missing value added to match Bridge spec (13 values total)
  { value: 'personal_or_living_expenses',            label: 'Gastos personales / manutención' },
  { value: 'tax_optimization',                       label: 'Optimización fiscal' },
  { value: 'third_party_money_transmission',         label: 'Transmisión de fondos de terceros' },
  { value: 'other',                                  label: 'Otro' },
] as const

export type BusinessAccountPurpose = typeof BUSINESS_ACCOUNT_PURPOSE[number]['value']

// ─── Countries — ISO 3166-1 alpha-3 (lista reducida LAC + principales) ───────
export const BRIDGE_COUNTRIES = [
  { value: 'ARG', label: 'Argentina' },
  { value: 'BOL', label: 'Bolivia' },
  { value: 'BRA', label: 'Brasil' },
  { value: 'CAN', label: 'Canadá' },
  { value: 'CHL', label: 'Chile' },
  { value: 'COL', label: 'Colombia' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'CUB', label: 'Cuba' },
  { value: 'DOM', label: 'República Dominicana' },
  { value: 'ECU', label: 'Ecuador' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'ESP', label: 'España' },
  { value: 'USA', label: 'Estados Unidos' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'HND', label: 'Honduras' },
  { value: 'MEX', label: 'México' },
  { value: 'NIC', label: 'Nicaragua' },
  { value: 'PAN', label: 'Panamá' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'PER', label: 'Perú' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'URY', label: 'Uruguay' },
  { value: 'VEN', label: 'Venezuela' },
  { value: 'GBR', label: 'Reino Unido' },
  { value: 'DEU', label: 'Alemania' },
  { value: 'FRA', label: 'Francia' },
  { value: 'ITA', label: 'Italia' },
  { value: 'CHN', label: 'China' },
  { value: 'JPN', label: 'Japón' },
  { value: 'KOR', label: 'Corea del Sur' },
  { value: 'IND', label: 'India' },
  { value: 'AUS', label: 'Australia' },
  { value: 'NZL', label: 'Nueva Zelanda' },
  { value: 'ZAF', label: 'Sudáfrica' },
  { value: 'NGA', label: 'Nigeria' },
  { value: 'KEN', label: 'Kenia' },
] as const

export type BridgeCountryCode = typeof BRIDGE_COUNTRIES[number]['value']

// ─── Helper: extract values only (for zod enum) ──────────────────────────────
export const BRIDGE_COUNTRY_CODES = BRIDGE_COUNTRIES.map(c => c.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_ID_TYPE_VALUES = INDIVIDUAL_ID_TYPES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_SOF_VALUES = INDIVIDUAL_SOURCE_OF_FUNDS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_PURPOSE_VALUES = INDIVIDUAL_ACCOUNT_PURPOSE.map(t => t.value) as unknown as readonly [string, ...string[]]
export const MONTHLY_PAYMENT_VALUES = EXPECTED_MONTHLY_PAYMENTS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_TYPE_VALUES = BUSINESS_TYPES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_SOF_VALUES = BUSINESS_SOURCE_OF_FUNDS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_PURPOSE_VALUES = BUSINESS_ACCOUNT_PURPOSE.map(t => t.value) as unknown as readonly [string, ...string[]]
// P1 / New exports
export const EMPLOYMENT_STATUS_VALUES = EMPLOYMENT_STATUS_OPTIONS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const ANNUAL_REVENUE_VALUES = ANNUAL_REVENUE_RANGES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const HIGH_RISK_ACTIVITY_VALUES = HIGH_RISK_ACTIVITIES.map(t => t.value) as unknown as readonly [string, ...string[]]

// ─── Dial codes — ISO 3166-1 alpha-3 → country calling code ─────────────────
export const COUNTRY_DIAL_CODES: Record<string, string> = {
  ARG: '+54',
  BOL: '+591',
  BRA: '+55',
  CAN: '+1',
  CHL: '+56',
  COL: '+57',
  CRI: '+506',
  CUB: '+53',
  DOM: '+1',
  ECU: '+593',
  SLV: '+503',
  ESP: '+34',
  USA: '+1',
  GTM: '+502',
  HND: '+504',
  MEX: '+52',
  NIC: '+505',
  PAN: '+507',
  PRY: '+595',
  PER: '+51',
  PRT: '+351',
  URY: '+598',
  VEN: '+58',
  GBR: '+44',
  DEU: '+49',
  FRA: '+33',
  ITA: '+39',
  CHN: '+86',
  JPN: '+81',
  KOR: '+82',
  IND: '+91',
  AUS: '+61',
  NZL: '+64',
  ZAF: '+27',
  NGA: '+234',
  KEN: '+254',
}
