/**
 * bridge-constants.ts
 * Valores exactos aceptados por la API de Bridge (https://apidocs.bridge.xyz)
 * Usar siempre estos valores en los formularios de KYC/KYB — nunca texto libre.
 */

// ─── Tipos de documento de identificación aceptados por Bridge ───────────────
export const INDIVIDUAL_ID_TYPES = [
  { value: 'passport',               label: 'Pasaporte' },
  { value: 'national_id',            label: 'Cédula de Identidad / DNI' },
  { value: 'drivers_license',        label: 'Licencia de Conducir' },
  { value: 'permanent_residency_id', label: 'Residencia Permanente' },
  { value: 'state_or_provincial_id', label: 'ID Estatal o Provincial' },
  { value: 'military_id',            label: 'ID Militar' },
  { value: 'visa',                   label: 'Visa' },
] as const

export type IndividualIdType = typeof INDIVIDUAL_ID_TYPES[number]['value']

// ─── Tipo de identificación fiscal (para UBOs y empresas) ───────────────────
export const TAX_ID_TYPES = [
  { value: 'ssn',   label: 'SSN (EE.UU.)' },
  { value: 'ein',   label: 'EIN (EE.UU. - Empresa)' },
  { value: 'tin',   label: 'TIN (Número de Identificación Tributaria)' },
  { value: 'nit',   label: 'NIT (Bolivia)' },
  { value: 'cpf',   label: 'CPF (Brasil)' },
  { value: 'cnpj',  label: 'CNPJ (Brasil - Empresa)' },
  { value: 'ruc',   label: 'RUC' },
  { value: 'cc',    label: 'Cédula de Ciudadanía' },
  { value: 'curp',  label: 'CURP (México)' },
  { value: 'rfc',   label: 'RFC (México)' },
  { value: 'other', label: 'Otro' },
] as const

// ─── Source of funds — Individual ─────────────────────────────────────────────
// IMPORTANTE: Valores alineados con Bridge API enum (actualizado según OpenAPI spec)
export const INDIVIDUAL_SOURCE_OF_FUNDS = [
  { value: 'salary',                      label: 'Salario / Nómina' },
  { value: 'savings',                     label: 'Ahorros' },
  { value: 'company_funds',               label: 'Fondos empresariales' },
  { value: 'investments_loans',           label: 'Inversiones / Préstamos' },
  { value: 'government_benefits',         label: 'Beneficios gubernamentales' },
  { value: 'pension_retirement',          label: 'Pensión / Jubilación' },
  { value: 'inheritance',                 label: 'Herencia' },
  { value: 'gifts',                       label: 'Donación / Regalo' },
  { value: 'sale_of_assets_real_estate',  label: 'Venta de activos / inmuebles' },
  { value: 'ecommerce_reseller',          label: 'Revendedor / E-commerce' },
  { value: 'someone_elses_funds',         label: 'Fondos de terceros' },
  { value: 'gambling_proceeds',           label: 'Ingresos de juegos de azar' },
] as const

export type IndividualSourceOfFunds = typeof INDIVIDUAL_SOURCE_OF_FUNDS[number]['value']

// ─── Account purpose — Individual ─────────────────────────────────────────────
// IMPORTANTE: Valores alineados con Bridge API enum (actualizado según OpenAPI spec)
export const INDIVIDUAL_ACCOUNT_PURPOSE = [
  { value: 'payments_to_friends_or_family_abroad', label: 'Pagos a familia / amigos en el extranjero' },
  { value: 'personal_or_living_expenses',          label: 'Gastos personales / de vida' },
  { value: 'receive_salary',                       label: 'Recibir salario' },
  { value: 'purchase_goods_and_services',          label: 'Compra de bienes y servicios' },
  { value: 'receive_payment_for_freelancing',      label: 'Cobros por trabajo freelance' },
  { value: 'investment_purposes',                  label: 'Inversiones' },
  { value: 'operating_a_company',                  label: 'Operación de una empresa' },
  { value: 'ecommerce_retail_payments',            label: 'Pagos e-commerce / retail' },
  { value: 'charitable_donations',                 label: 'Donaciones benéficas' },
  { value: 'protect_wealth',                       label: 'Protección de patrimonio' },
  { value: 'other',                                label: 'Otro' },
] as const

export type IndividualAccountPurpose = typeof INDIVIDUAL_ACCOUNT_PURPOSE[number]['value']

// ─── Expected monthly payments — Individual & Business ───────────────────────
// Valores exactos del enum Bridge según OpenAPI spec (actualizados)
export const EXPECTED_MONTHLY_PAYMENTS = [
  { value: '0_4999',      label: 'Menos de $5,000 USD/mes' },
  { value: '5000_9999',   label: '$5,000 – $9,999 USD/mes' },
  { value: '10000_49999', label: '$10,000 – $49,999 USD/mes' },
  { value: '50000_plus',  label: '$50,000+ USD/mes' },
] as const

export type ExpectedMonthlyPayments = typeof EXPECTED_MONTHLY_PAYMENTS[number]['value']

// ─── Estimated annual revenue — Business (P1 high-risk) ──────────────────────
// Valores exactos del enum Bridge OpenAPI spec
export const ANNUAL_REVENUE_RANGES = [
  { value: '0_99999',             label: 'Menos de $100,000 USD/año' },
  { value: '100000_999999',       label: '$100,000 – $999,999 USD/año' },
  { value: '1000000_9999999',     label: '$1M – $9.9M USD/año' },
  { value: '10000000_49999999',   label: '$10M – $49.9M USD/año' },
  { value: '50000000_249999999',  label: '$50M – $249M USD/año' },
  { value: '250000000_plus',      label: '$250M+ USD/año' },
] as const

export type AnnualRevenueRange = typeof ANNUAL_REVENUE_RANGES[number]['value']

// ─── Employment status — Individual (P1 high-risk) ────────────────────────────
// Valores exactos Bridge API OpenAPI spec (agregado: homemaker; removido: other)
export const EMPLOYMENT_STATUS_OPTIONS = [
  { value: 'employed',      label: 'Empleado (relación de dependencia)' },
  { value: 'self_employed', label: 'Independiente / Autónomo' },
  { value: 'unemployed',    label: 'Desempleado' },
  { value: 'student',       label: 'Estudiante' },
  { value: 'retired',       label: 'Jubilado / Retirado' },
  { value: 'homemaker',     label: 'Amo/a de casa' },
] as const

export type EmploymentStatus = typeof EMPLOYMENT_STATUS_OPTIONS[number]['value']

// ─── Most Recent Occupation — Individual (required for restricted countries/high-risk) ──
// Códigos O*NET-SOC exactos aceptados por Bridge API
// Ref: https://apidocs.bridge.xyz/platform/customers/compliance/sof-eu-most-recent-occupation-list
// IMPORTANTE: estos son los únicos códigos válidos — no usar valores inventados
// Última sincronización: 2026-04-21 — 570 códigos oficiales
export const OCCUPATION_OPTIONS = [
  // ── Gerencia y Dirección ──
  { value: '111011', label: 'Chief Executive / Ejecutivo y Director General' },
  { value: '111021', label: 'General and Operations Manager / Gerente de Operaciones' },
  { value: '111031', label: 'Legislator / Legislador' },
  { value: '112011', label: 'Advertising and Promotions Manager / Gerente de Publicidad' },
  { value: '112021', label: 'Marketing Manager / Gerente de Marketing' },
  { value: '112022', label: 'Sales Manager / Gerente de Ventas' },
  { value: '112030', label: 'Public Relations and Fundraising Manager / Gerente de Relaciones Públicas' },
  { value: '113012', label: 'Administrative Services Manager / Gerente Administrativo' },
  { value: '113013', label: 'Facilities Manager / Gerente de Instalaciones' },
  { value: '113021', label: 'Computer and Information Systems Manager / Gerente de Sistemas' },
  { value: '113031', label: 'Financial Manager / Gerente Financiero' },
  { value: '113051', label: 'Industrial Production Manager / Gerente de Producción' },
  { value: '113061', label: 'Purchasing Manager / Gerente de Compras' },
  { value: '113071', label: 'Transportation, Storage, and Distribution Manager / Gerente de Transporte' },
  { value: '113111', label: 'Compensation and Benefits Manager / Gerente de Compensaciones' },
  { value: '113121', label: 'Human Resources Manager / Gerente de Recursos Humanos' },
  { value: '113131', label: 'Training and Development Manager / Gerente de Capacitación' },
  { value: '119013', label: 'Farmer, Rancher, and Other Agricultural Manager / Agricultor y Ganadero' },
  { value: '119021', label: 'Construction Manager / Gerente de Construcción' },
  { value: '119030', label: 'Education and Childcare Administrator / Administrador Educativo' },
  { value: '119041', label: 'Architectural and Engineering Manager / Gerente de Ingeniería' },
  { value: '119051', label: 'Food Service Manager / Gerente de Servicio de Alimentos' },
  { value: '119070', label: 'Entertainment and Recreation Manager / Gerente de Entretenimiento' },
  { value: '119081', label: 'Lodging Manager / Gerente de Alojamiento' },
  { value: '119111', label: 'Medical and Health Services Manager / Gerente de Servicios de Salud' },
  { value: '119121', label: 'Natural Sciences Manager / Gerente de Ciencias Naturales' },
  { value: '119131', label: 'Postmaster and Mail Superintendent / Director Postal' },
  { value: '119141', label: 'Property, Real Estate, and Community Association Manager / Gerente Inmobiliario' },
  { value: '119151', label: 'Social and Community Service Manager / Gerente de Servicios Comunitarios' },
  { value: '119161', label: 'Emergency Management Director / Director de Emergencias' },
  { value: '119171', label: 'Funeral Home Manager / Gerente de Funeraria' },
  { value: '119179', label: 'Personal Service Manager, Other / Gerente de Servicios Personales' },
  { value: '119199', label: 'Manager, Other / Otro Gerente' },
  // ── Finanzas y Negocios ──
  { value: '131011', label: 'Agent and Business Manager / Agente y Representante' },
  { value: '131021', label: 'Buyer and Purchasing Agent, Farm Products / Agente de Compras Agrícolas' },
  { value: '131022', label: 'Wholesale and Retail Buyer / Comprador Mayorista y Minorista' },
  { value: '131023', label: 'Purchasing Agent / Agente de Compras' },
  { value: '131030', label: 'Claims Adjuster, Appraiser, Examiner / Ajustador de Seguros' },
  { value: '131041', label: 'Compliance Officer / Oficial de Cumplimiento' },
  { value: '131051', label: 'Cost Estimator / Estimador de Costos' },
  { value: '131070', label: 'Human Resources Worker / Recursos Humanos' },
  { value: '131081', label: 'Logistician / Logístico' },
  { value: '131082', label: 'Project Management Specialist / Especialista en Gestión de Proyectos' },
  { value: '131111', label: 'Management Analyst / Analista de Gestión' },
  { value: '131121', label: 'Meeting, Convention, and Event Planner / Organizador de Eventos' },
  { value: '131131', label: 'Fundraiser / Recaudador de Fondos' },
  { value: '131141', label: 'Compensation, Benefits, and Job Analysis Specialist / Especialista en Compensaciones' },
  { value: '131151', label: 'Training and Development Specialist / Especialista en Capacitación' },
  { value: '131161', label: 'Market Research Analyst / Analista de Investigación de Mercado' },
  { value: '131199', label: 'Business Operations Specialist, Other / Otro Especialista en Operaciones' },
  { value: '132011', label: 'Accountant and Auditor / Contador y Auditor' },
  { value: '132020', label: 'Property Appraiser and Assessor / Evaluador y Tasador' },
  { value: '132031', label: 'Budget Analyst / Analista de Presupuesto' },
  { value: '132041', label: 'Credit Analyst / Analista de Crédito' },
  { value: '132051', label: 'Financial and Investment Analyst / Analista Financiero' },
  { value: '132052', label: 'Personal Financial Advisor / Asesor Financiero Personal' },
  { value: '132053', label: 'Insurance Underwriter / Suscriptor de Seguros' },
  { value: '132061', label: 'Financial Examiner / Examinador Financiero' },
  { value: '132070', label: 'Credit Counselor and Loan Officer / Oficial de Crédito' },
  { value: '132081', label: 'Tax Examiner and Collector / Inspector Fiscal' },
  { value: '132082', label: 'Tax Preparer / Preparador de Impuestos' },
  { value: '1320XX', label: 'Other Financial Specialist / Otro Especialista Financiero' },
  // ── Ciencias Computacionales ──
  { value: '151211', label: 'Computer Systems Analyst / Analista de Sistemas' },
  { value: '151212', label: 'Information Security Analyst / Analista de Seguridad Informática' },
  { value: '151221', label: 'Computer and Information Research Scientist / Investigador en Sistemas' },
  { value: '151230', label: 'Computer Support Specialist / Soporte Técnico' },
  { value: '151241', label: 'Computer Network Architect / Arquitecto de Redes' },
  { value: '151244', label: 'Network and Computer Systems Administrator / Administrador de Redes' },
  { value: '15124X', label: 'Database Administrator and Architect / Administrador de Base de Datos' },
  { value: '151251', label: 'Computer Programmer / Programador' },
  { value: '151252', label: 'Software Developer / Desarrollador de Software' },
  { value: '151253', label: 'Software Quality Assurance Analyst and Tester / QA Analista' },
  { value: '151254', label: 'Web Developer / Desarrollador Web' },
  { value: '151255', label: 'Web and Digital Interface Designer / Diseñador Web' },
  { value: '151299', label: 'Computer Occupation, Other / Otra Ocupación en Computación' },
  // ── Matemáticas ──
  { value: '152011', label: 'Actuary / Actuario' },
  { value: '152021', label: 'Mathematician / Matemático' },
  { value: '152031', label: 'Operations Research Analyst / Analista de Operaciones' },
  { value: '152041', label: 'Statistician / Estadístico' },
  { value: '1520XX', label: 'Other Mathematical Science Occupation / Otra Ciencia Matemática' },
  // ── Ingeniería ──
  { value: '171011', label: 'Architect, except Landscape and Naval / Arquitecto' },
  { value: '171012', label: 'Landscape Architect / Arquitecto Paisajista' },
  { value: '171020', label: 'Surveyor, Cartographer, and Photogrammetrist / Topógrafo y Cartógrafo' },
  { value: '172011', label: 'Aerospace Engineer / Ingeniero Aeroespacial' },
  { value: '172021', label: 'Agricultural Engineer / Ingeniero Agrícola' },
  { value: '172031', label: 'Bioengineer and Biomedical Engineer / Bioingeniero' },
  { value: '172041', label: 'Chemical Engineer / Ingeniero Químico' },
  { value: '172051', label: 'Civil Engineer / Ingeniero Civil' },
  { value: '172061', label: 'Computer Hardware Engineer / Ingeniero de Hardware' },
  { value: '172070', label: 'Electrical and Electronics Engineer / Ingeniero Eléctrico' },
  { value: '172081', label: 'Environmental Engineer / Ingeniero Ambiental' },
  { value: '172110', label: 'Industrial Engineer / Ingeniero Industrial' },
  { value: '172121', label: 'Marine Engineer and Naval Architect / Ingeniero Naval' },
  { value: '172131', label: 'Materials Engineer / Ingeniero de Materiales' },
  { value: '172141', label: 'Mechanical Engineer / Ingeniero Mecánico' },
  { value: '172151', label: 'Mining and Geological Engineer / Ingeniero de Minería' },
  { value: '172161', label: 'Nuclear Engineer / Ingeniero Nuclear' },
  { value: '172171', label: 'Petroleum Engineer / Ingeniero Petrolero' },
  { value: '172199', label: 'Engineer, Other / Otro Ingeniero' },
  { value: '173011', label: 'Architectural and Civil Drafter / Dibujante Arquitectónico' },
  { value: '173023', label: 'Electrical and Electronic Engineering Technician / Técnico Electrónico' },
  { value: '173031', label: 'Surveying and Mapping Technician / Técnico Topógrafo' },
  { value: '17301X', label: 'Other Drafter / Otro Dibujante Técnico' },
  { value: '17302X', label: 'Other Engineering Technologist and Technician / Otro Técnico en Ingeniería' },
  // ── Ciencias Naturales ──
  { value: '191010', label: 'Agricultural and Food Scientist / Científico Agrícola y Alimentario' },
  { value: '191020', label: 'Biological Scientist / Biólogo' },
  { value: '191030', label: 'Conservation Scientist and Forester / Científico Ambiental y Forestal' },
  { value: '191040', label: 'Medical Scientist / Científico Médico' },
  { value: '191099', label: 'Life Scientist, Other / Otro Científico de Vida' },
  { value: '192010', label: 'Astronomer and Physicist / Astrónomo y Físico' },
  { value: '192021', label: 'Atmospheric and Space Scientist / Científico Atmosférico' },
  { value: '192030', label: 'Chemist and Materials Scientist / Químico' },
  { value: '192041', label: 'Environmental Scientist / Científico Ambiental' },
  { value: '19204X', label: 'Geoscientist and Hydrologist / Geocientífico e Hidrólogo' },
  { value: '192099', label: 'Physical Scientist, Other / Otro Científico Físico' },
  { value: '193011', label: 'Economist / Economista' },
  { value: '193022', label: 'Survey Researcher / Investigador de Encuestas' },
  { value: '193033', label: 'Clinical and Counseling Psychologist / Psicólogo Clínico' },
  { value: '193034', label: 'School Psychologist / Psicólogo Escolar' },
  { value: '193041', label: 'Sociologist / Sociólogo' },
  { value: '193051', label: 'Urban and Regional Planner / Planificador Urbano' },
  { value: '193090', label: 'Miscellaneous Social Scientist / Otro Científico Social' },
  { value: '19303X', label: 'Other Psychologist / Otro Psicólogo' },
  { value: '194010', label: 'Agricultural and Food Science Technician / Técnico en Ciencias Agrícolas' },
  { value: '194021', label: 'Biological Technician / Técnico Biólogo' },
  { value: '194031', label: 'Chemical Technician / Técnico Químico' },
  { value: '194040', label: 'Environmental Science and Geoscience Technician / Técnico Ambiental' },
  { value: '194051', label: 'Nuclear Technician / Técnico Nuclear' },
  { value: '194061', label: 'Social Science Research Assistant / Asistente de Investigación Social' },
  { value: '195010', label: 'Occupational Health and Safety Specialist / Especialista en Seguridad Laboral' },
  { value: '1940XX', label: 'Other Life, Physical, and Social Science Technician / Otro Técnico Científico' },
  // ── Trabajo Social y Consejería ──
  { value: '211011', label: 'Substance Abuse and Behavioral Disorder Counselor / Consejero de Adicciones' },
  { value: '211012', label: 'Educational, Guidance, and Career Counselor / Orientador Educativo' },
  { value: '211013', label: 'Marriage and Family Therapist / Terapeuta Familiar' },
  { value: '211014', label: 'Mental Health Counselor / Consejero de Salud Mental' },
  { value: '211015', label: 'Rehabilitation Counselor / Consejero de Rehabilitación' },
  { value: '211019', label: 'Counselor, Other / Otro Consejero' },
  { value: '211021', label: 'Child, Family, and School Social Worker / Trabajador Social' },
  { value: '211022', label: 'Healthcare Social Worker / Trabajador Social de Salud' },
  { value: '211023', label: 'Mental Health and Substance Abuse Social Worker / Trabajador Social de Salud Mental' },
  { value: '211029', label: 'Social Worker, Other / Otro Trabajador Social' },
  { value: '211092', label: 'Probation Officer and Correctional Treatment Specialist / Oficial de Libertad Condicional' },
  { value: '211093', label: 'Social and Human Service Assistant / Asistente de Servicio Social' },
  { value: '21109X', label: 'Other Community and Social Service Specialist / Otro Especialista Social' },
  { value: '212011', label: 'Clergy / Clero' },
  { value: '212021', label: 'Director, Religious Activities and Education / Director Religioso' },
  { value: '212099', label: 'Religious Worker, Other / Otro Trabajador Religioso' },
  // ── Educación ──
  { value: '251000', label: 'Postsecondary Teacher / Profesor Universitario' },
  { value: '252010', label: 'Preschool and Kindergarten Teacher / Maestro Preescolar' },
  { value: '252020', label: 'Elementary and Middle School Teacher / Maestro de Primaria' },
  { value: '252030', label: 'Secondary School Teacher / Maestro de Secundaria' },
  { value: '252050', label: 'Special Education Teacher / Maestro de Educación Especial' },
  { value: '253041', label: 'Tutor / Tutor' },
  { value: '254010', label: 'Archivist, Curator, and Museum Technician / Archivista y Curador' },
  { value: '254022', label: 'Librarian and Media Collections Specialist / Bibliotecario' },
  { value: '254031', label: 'Library Technician / Técnico de Biblioteca' },
  { value: '259040', label: 'Teaching Assistant / Asistente de Enseñanza' },
  { value: '2530XX', label: 'Other Teacher and Instructor / Otro Maestro' },
  { value: '2590XX', label: 'Other Educational Instruction and Library Worker / Otro Trabajador Educativo' },
  // ── Legal ──
  { value: '231011', label: 'Lawyer / Abogado' },
  { value: '231012', label: 'Judicial Law Clerk / Asistente Judicial' },
  { value: '231020', label: 'Judge, Magistrate, and Other Judicial Worker / Juez y Magistrado' },
  { value: '232011', label: 'Paralegal and Legal Assistant / Paralegal' },
  { value: '232093', label: 'Title Examiner, Abstractor, and Searcher / Examinador de Títulos' },
  { value: '232099', label: 'Legal Support Worker, Other / Otro Apoyo Legal' },
  // ── Arte, Diseño y Media ──
  { value: '271010', label: 'Artist and Related Worker / Artista' },
  { value: '271021', label: 'Commercial and Industrial Designer / Diseñador Comercial' },
  { value: '271022', label: 'Fashion Designer / Diseñador de Moda' },
  { value: '271023', label: 'Floral Designer / Diseñador Floral' },
  { value: '271024', label: 'Graphic Designer / Diseñador Gráfico' },
  { value: '271025', label: 'Interior Designer / Diseñador de Interiores' },
  { value: '271026', label: 'Merchandise Displayer and Window Trimmer / Vitrinista' },
  { value: '27102X', label: 'Other Designer / Otro Diseñador' },
  { value: '272011', label: 'Actor / Actor' },
  { value: '272012', label: 'Producer and Director / Productor y Director' },
  { value: '272021', label: 'Athlete and Sports Competitor / Atleta' },
  { value: '272022', label: 'Coach and Scout / Entrenador Deportivo' },
  { value: '272023', label: 'Umpire, Referee, and Other Sports Official / Árbitro' },
  { value: '272030', label: 'Dancer and Choreographer / Bailarín y Coreógrafo' },
  { value: '272041', label: 'Music Director and Composer / Director Musical y Compositor' },
  { value: '272042', label: 'Musician and Singer / Músico y Cantante' },
  { value: '272091', label: 'Disc Jockey, except Radio / DJ' },
  { value: '272099', label: 'Entertainer and Performer, Other / Otro Artista' },
  { value: '273011', label: 'Broadcast Announcer and Radio Disc Jockey / Locutor de Radio' },
  { value: '273023', label: 'News Analyst, Reporter, and Journalist / Periodista' },
  { value: '273031', label: 'Public Relations Specialist / Especialista en RR.PP.' },
  { value: '273041', label: 'Editor / Editor' },
  { value: '273042', label: 'Technical Writer / Escritor Técnico' },
  { value: '273043', label: 'Writer and Author / Escritor' },
  { value: '273091', label: 'Interpreter and Translator / Intérprete y Traductor' },
  { value: '273092', label: 'Court Reporter and Simultaneous Captioner / Taquígrafo Judicial' },
  { value: '273099', label: 'Media and Communication Worker, Other / Otro Comunicador' },
  { value: '274010', label: 'Broadcast, Sound, and Lighting Technician / Técnico de Transmisión' },
  { value: '274021', label: 'Photographer / Fotógrafo' },
  { value: '274030', label: 'Television, Video, and Film Camera Operator and Editor / Camarógrafo' },
  { value: '274099', label: 'Media and Communication Equipment Worker, Other / Otro Técnico de Medios' },
  // ── Salud — Profesionales ──
  { value: '291011', label: 'Chiropractor / Quiropráctico' },
  { value: '291020', label: 'Dentist / Dentista' },
  { value: '291031', label: 'Dietitian and Nutritionist / Nutricionista' },
  { value: '291041', label: 'Optometrist / Optometrista' },
  { value: '291051', label: 'Pharmacist / Farmacéutico' },
  { value: '291071', label: 'Physician Assistant / Asistente Médico' },
  { value: '291081', label: 'Podiatrist / Podólogo' },
  { value: '291122', label: 'Occupational Therapist / Terapeuta Ocupacional' },
  { value: '291123', label: 'Physical Therapist / Fisioterapeuta' },
  { value: '291124', label: 'Radiation Therapist / Radioterapeuta' },
  { value: '291125', label: 'Recreational Therapist / Terapeuta Recreativo' },
  { value: '291126', label: 'Respiratory Therapist / Terapeuta Respiratorio' },
  { value: '291127', label: 'Speech-Language Pathologist / Patólogo del Habla' },
  { value: '291128', label: 'Exercise Physiologist / Fisiólogo del Ejercicio' },
  { value: '291129', label: 'Therapist, Other / Otro Terapeuta' },
  { value: '291131', label: 'Veterinarian / Veterinario' },
  { value: '291141', label: 'Registered Nurse / Enfermero Registrado' },
  { value: '291151', label: 'Nurse Anesthetist / Enfermero Anestesista' },
  { value: '291161', label: 'Nurse Midwife / Enfermera Partera' },
  { value: '291171', label: 'Nurse Practitioner / Enfermero Profesional' },
  { value: '291181', label: 'Audiologist / Audiólogo' },
  { value: '291214', label: 'Emergency Medicine Physician / Médico de Emergencias' },
  { value: '291224', label: 'Radiologist / Radiólogo' },
  { value: '291240', label: 'Surgeon / Cirujano' },
  { value: '291291', label: 'Acupuncturist / Acupunturista' },
  { value: '291292', label: 'Dental Hygienist / Higienista Dental' },
  { value: '291299', label: 'Healthcare Practitioner, Other / Otro Profesional de Salud' },
  { value: '2912XX', label: 'Other Physician / Otro Médico' },
  // ── Salud — Técnicos ──
  { value: '292010', label: 'Clinical Laboratory Technologist and Technician / Laboratorista Clínico' },
  { value: '292031', label: 'Cardiovascular Technologist and Technician / Técnico Cardiovascular' },
  { value: '292032', label: 'Diagnostic Medical Sonographer / Ultrasonografista' },
  { value: '292034', label: 'Radiologic Technologist and Technician / Técnico Radiólogo' },
  { value: '292035', label: 'Magnetic Resonance Imaging Technologist / Técnico de Resonancia Magnética' },
  { value: '292042', label: 'Emergency Medical Technician / Técnico de Emergencias' },
  { value: '292043', label: 'Paramedic / Paramédico' },
  { value: '292052', label: 'Pharmacy Technician / Técnico de Farmacia' },
  { value: '292053', label: 'Psychiatric Technician / Técnico Psiquiátrico' },
  { value: '292055', label: 'Surgical Technologist / Tecnólogo Quirúrgico' },
  { value: '292056', label: 'Veterinary Technologist and Technician / Técnico Veterinario' },
  { value: '292061', label: 'Licensed Practical and Licensed Vocational Nurse / Enfermero Práctico' },
  { value: '292072', label: 'Medical Records Specialist / Especialista en Registros Médicos' },
  { value: '292081', label: 'Optician, Dispensing / Óptico' },
  { value: '292090', label: 'Miscellaneous Health Technologist and Technician / Otro Técnico de Salud' },
  { value: '29203X', label: 'Nuclear Medicine Technologist and Medical Dosimetrist / Técnico de Medicina Nuclear' },
  { value: '29205X', label: 'Dietetic Technician and Ophthalmic Medical Technician / Técnico Dietético y Oftalmológico' },
  { value: '299000', label: 'Other Healthcare Practitioner and Technical Occupation / Otro Profesional Sanitario' },
  // ── Apoyo Sanitario ──
  { value: '311121', label: 'Home Health Aide / Asistente de Salud a Domicilio' },
  { value: '311131', label: 'Nursing Assistant / Asistente de Enfermería' },
  { value: '31113X', label: 'Orderly and Psychiatric Aide / Asistente Psiquiátrico' },
  { value: '312010', label: 'Occupational Therapy Assistant and Aide / Asistente de Terapia Ocupacional' },
  { value: '312020', label: 'Physical Therapist Assistant and Aide / Asistente de Fisioterapia' },
  { value: '319011', label: 'Massage Therapist / Masajista' },
  { value: '319091', label: 'Dental Assistant / Asistente Dental' },
  { value: '319092', label: 'Medical Assistant / Asistente Médico' },
  { value: '319094', label: 'Medical Transcriptionist / Transcriptor Médico' },
  { value: '319095', label: 'Pharmacy Aide / Asistente de Farmacia' },
  { value: '319096', label: 'Veterinary Assistant and Laboratory Animal Caretaker / Asistente Veterinario' },
  { value: '319097', label: 'Phlebotomist / Flebotomista' },
  { value: '31909X', label: 'Other Healthcare Support Worker / Otro Apoyo Sanitario' },
  // ── Protección y Seguridad ──
  { value: '331011', label: 'First-Line Supervisor of Correctional Officer / Supervisor Penitenciario' },
  { value: '331012', label: 'First-Line Supervisor of Police and Detective / Supervisor de Policía' },
  { value: '331021', label: 'First-Line Supervisor of Firefighting and Prevention Worker / Supervisor de Bomberos' },
  { value: '331091', label: 'First-Line Supervisor of Security Worker / Supervisor de Seguridad' },
  { value: '331099', label: 'First-Line Supervisor of Protective Service Worker, Other / Otro Supervisor de Protección' },
  { value: '332011', label: 'Firefighter / Bombero' },
  { value: '332020', label: 'Fire Inspector / Inspector de Incendios' },
  { value: '333011', label: 'Bailiff / Alguacil' },
  { value: '333012', label: 'Correctional Officer and Jailer / Oficial Penitenciario' },
  { value: '333021', label: 'Detective and Criminal Investigator / Detective' },
  { value: '333031', label: 'Fish and Game Warden / Guardabosques' },
  { value: '333041', label: 'Parking Enforcement Worker / Agente de Estacionamiento' },
  { value: '333050', label: 'Police Officer / Oficial de Policía' },
  { value: '339011', label: 'Animal Control Worker / Control Animal' },
  { value: '339021', label: 'Private Detective and Investigator / Detective Privado' },
  { value: '339030', label: 'Security Guard and Gambling Surveillance Officer / Guardia de Seguridad' },
  { value: '339091', label: 'Crossing Guard and Flagger / Guardia de Cruce' },
  { value: '339093', label: 'Transportation Security Screener / Inspector de Seguridad de Transporte' },
  { value: '339094', label: 'School Bus Monitor / Monitor de Autobús Escolar' },
  { value: '33909X', label: 'Other Protective Service Worker / Otro Trabajador de Protección' },
  // ── Alimentos y Servicios ──
  { value: '351011', label: 'Chef and Head Cook / Jefe de Cocina' },
  { value: '351012', label: 'First-Line Supervisor of Food Preparation and Serving Workers / Supervisor de Alimentos' },
  { value: '352010', label: 'Cook / Cocinero' },
  { value: '352021', label: 'Food Preparation Worker / Preparador de Alimentos' },
  { value: '353011', label: 'Bartender / Cantinero' },
  { value: '353023', label: 'Fast Food and Counter Worker / Empleado de Comida Rápida' },
  { value: '353031', label: 'Waiter or Waitress / Mesero' },
  { value: '353041', label: 'Food Server, Nonrestaurant / Servidor de Alimentos' },
  { value: '359011', label: 'Dining Room and Cafeteria Attendant / Ayudante de Cafetería' },
  { value: '359021', label: 'Dishwasher / Lavaplatos' },
  { value: '359031', label: 'Host and Hostess / Anfitrión de Restaurante' },
  { value: '359099', label: 'Food Preparation and Serving Related Worker, Other / Otro en Alimentos' },
  // ── Limpieza y Jardinería ──
  { value: '371011', label: 'First-Line Supervisor of Housekeeping and Janitorial Workers / Supervisor de Limpieza' },
  { value: '371012', label: 'First-Line Supervisor of Landscaping Workers / Supervisor de Jardinería' },
  { value: '37201X', label: 'Janitor and Building Cleaner / Conserje y Limpiador' },
  { value: '372012', label: 'Maids and Housekeeping Cleaner / Mucama' },
  { value: '372021', label: 'Pest Control Worker / Control de Plagas' },
  { value: '373011', label: 'Landscaping and Groundskeeping Worker / Jardinero' },
  { value: '373013', label: 'Tree Trimmer and Pruner / Podador de Árboles' },
  { value: '37301X', label: 'Other Grounds Maintenance Worker / Otro Mantenimiento de Jardines' },
  // ── Cuidado Personal y Servicios ──
  { value: '391000', label: 'Supervisor of Personal Care and Service Worker / Supervisor de Servicios Personales' },
  { value: '392011', label: 'Animal Trainer / Entrenador de Animales' },
  { value: '392021', label: 'Animal Caretaker / Cuidador de Animales' },
  { value: '393010', label: 'Gambling Services Worker / Trabajador de Servicios de Juego' },
  { value: '393031', label: 'Usher, Lobby Attendant, and Ticket Taker / Acomodador' },
  { value: '394031', label: 'Mortician, Undertaker, and Funeral Arranger / Funerario' },
  { value: '395011', label: 'Barber / Barbero' },
  { value: '395012', label: 'Hairdresser, Hairstylist, and Cosmetologist / Estilista y Cosmetólogo' },
  { value: '395092', label: 'Manicurist and Pedicurist / Manicurista' },
  { value: '395094', label: 'Skincare Specialist / Especialista en Cuidado de Piel' },
  { value: '396010', label: 'Baggage Porter, Bellhop, and Concierge / Botones y Concierge' },
  { value: '397010', label: 'Tour and Travel Guide / Guía Turístico' },
  { value: '399011', label: 'Childcare Worker / Cuidador de Niños' },
  { value: '399031', label: 'Exercise Trainer and Group Fitness Instructor / Instructor de Fitness' },
  { value: '399032', label: 'Recreation Worker / Trabajador de Recreación' },
  { value: '399041', label: 'Residential Advisor / Asesor Residencial' },
  { value: '399099', label: 'Personal Care and Service Worker, Other / Otro Servicio Personal' },
  { value: '3930XX', label: 'Other Entertainment Attendant and Related Worker / Otro de Entretenimiento' },
  { value: '3940XX', label: 'Embalmer, Crematory Operator and Funeral Attendant / Embalsamador' },
  { value: '39509X', label: 'Other Personal Appearance Worker / Otro de Apariencia Personal' },
  // ── Ventas ──
  { value: '411011', label: 'First-Line Supervisor of Retail Sales Workers / Supervisor de Ventas Minoristas' },
  { value: '411012', label: 'First-Line Supervisor of Non-Retail Sales Workers / Supervisor de Ventas' },
  { value: '412010', label: 'Cashier / Cajero' },
  { value: '412021', label: 'Counter and Rental Clerk / Empleado de Mostrador' },
  { value: '412022', label: 'Parts Salesperson / Vendedor de Repuestos' },
  { value: '412031', label: 'Retail Salesperson / Vendedor al Detalle' },
  { value: '413011', label: 'Advertising Sales Agent / Agente de Ventas Publicitarias' },
  { value: '413021', label: 'Insurance Sales Agent / Agente de Seguros' },
  { value: '413031', label: 'Securities, Commodities, and Financial Services Sales Agent / Agente Financiero' },
  { value: '413041', label: 'Travel Agent / Agente de Viajes' },
  { value: '413091', label: 'Sales Representative of Services / Representante de Ventas' },
  { value: '414010', label: 'Sales Representatives, Wholesale and Manufacturing / Representante Comercial' },
  { value: '419010', label: 'Model, Demonstrator, and Product Promoter / Promotor de Productos' },
  { value: '419020', label: 'Real Estate Broker and Sales Agent / Corredor de Bienes Raíces' },
  { value: '419031', label: 'Sales Engineer / Ingeniero de Ventas' },
  { value: '419041', label: 'Telemarketer / Televendedor' },
  { value: '419091', label: 'Door-to-Door Sales Worker / Vendedor a Domicilio' },
  { value: '419099', label: 'Sales and Related Worker, Other / Otro Vendedor' },
  // ── Oficina y Administración ──
  { value: '431011', label: 'First-Line Supervisor of Office and Administrative Support Workers / Supervisor Administrativo' },
  { value: '432011', label: 'Switchboard Operator / Telefonista' },
  { value: '432021', label: 'Telephone Operator / Operador Telefónico' },
  { value: '432099', label: 'Communications Equipment Operator, Other / Otro Operador de Comunicaciones' },
  { value: '433011', label: 'Bill and Account Collector / Cobrador' },
  { value: '433021', label: 'Billing and Posting Clerk / Empleado de Facturación' },
  { value: '433031', label: 'Bookkeeping, Accounting, and Auditing Clerk / Tenedor de Libros' },
  { value: '433041', label: 'Gambling Cage Worker / Cajero de Casino' },
  { value: '433051', label: 'Payroll and Timekeeping Clerk / Empleado de Nómina' },
  { value: '433061', label: 'Procurement Clerk / Empleado de Compras' },
  { value: '433071', label: 'Teller / Cajero Bancario' },
  { value: '433099', label: 'Financial Clerk, Other / Otro Empleado Financiero' },
  { value: '434011', label: 'Brokerage Clerk / Empleado de Corretaje' },
  { value: '434021', label: 'Correspondence Clerk / Empleado de Correspondencia' },
  { value: '434031', label: 'Court, Municipal, and License Clerk / Empleado de Juzgado' },
  { value: '434041', label: 'Credit Authorizer, Checker, and Clerk / Autorizador de Crédito' },
  { value: '434051', label: 'Customer Service Representative / Representante de Servicio al Cliente' },
  { value: '434061', label: 'Eligibility Interviewer / Entrevistador de Elegibilidad' },
  { value: '434071', label: 'File Clerk / Archivista' },
  { value: '434081', label: 'Hotel, Motel, and Resort Desk Clerk / Recepcionista de Hotel' },
  { value: '434111', label: 'Interviewer / Entrevistador' },
  { value: '434121', label: 'Library Assistant, Clerical / Asistente de Biblioteca' },
  { value: '434131', label: 'Loan Interviewer and Clerk / Empleado de Préstamos' },
  { value: '434141', label: 'New Accounts Clerk / Empleado de Cuentas Nuevas' },
  { value: '434151', label: 'Order Clerk / Empleado de Pedidos' },
  { value: '434161', label: 'Human Resources Assistant / Asistente de RRHH' },
  { value: '434171', label: 'Receptionist and Information Clerk / Recepcionista' },
  { value: '434181', label: 'Reservation and Transportation Ticket Agent and Travel Clerk / Agente de Reservas' },
  { value: '434199', label: 'Information and Record Clerk, Other / Otro Empleado de Registro' },
  { value: '435011', label: 'Cargo and Freight Agent / Agente de Carga' },
  { value: '435021', label: 'Courier and Messenger / Mensajero' },
  { value: '435031', label: 'Public Safety Telecommunicator / Despachador de Seguridad' },
  { value: '435032', label: 'Dispatcher / Despachador' },
  { value: '435041', label: 'Meter Reader, Utilities / Lector de Medidores' },
  { value: '435051', label: 'Postal Service Clerk / Empleado Postal' },
  { value: '435052', label: 'Postal Service Mail Carrier / Cartero' },
  { value: '435053', label: 'Postal Service Mail Sorter / Clasificador Postal' },
  { value: '435061', label: 'Production, Planning, and Expediting Clerk / Programador de Producción' },
  { value: '435071', label: 'Shipping, Receiving, and Inventory Clerk / Empleado de Envíos' },
  { value: '435111', label: 'Weigher, Measurer, Checker, and Sampler / Pesador y Verificador' },
  { value: '436011', label: 'Executive Secretary and Executive Administrative Assistant / Secretaria Ejecutiva' },
  { value: '436012', label: 'Legal Secretary and Administrative Assistant / Secretaria Legal' },
  { value: '436013', label: 'Medical Secretary and Administrative Assistant / Secretaria Médica' },
  { value: '436014', label: 'Secretary and Administrative Assistant / Secretaria General' },
  { value: '439021', label: 'Data Labeler and Data Entry Keyer / Capturista de Datos' },
  { value: '439022', label: 'Word Processor and Typist / Mecanógrafo' },
  { value: '439031', label: 'Desktop Publisher / Editor de Escritorio' },
  { value: '439041', label: 'Insurance Claims and Policy Processing Clerk / Empleado de Reclamaciones' },
  { value: '439051', label: 'Mail Clerk and Mail Machine Operator / Empleado de Correo' },
  { value: '439061', label: 'Office Clerk, General / Empleado de Oficina' },
  { value: '439071', label: 'Office Machine Operator / Operador de Máquinas de Oficina' },
  { value: '439081', label: 'Proofreader and Copy Marker / Corrector de Pruebas' },
  { value: '439111', label: 'Statistical Assistant / Asistente Estadístico' },
  { value: '439199', label: 'Office and Administrative Support Worker, Other / Otro Apoyo Administrativo' },
  // ── Agricultura ──
  { value: '451011', label: 'First-Line Supervisor of Farming, Fishing, and Forestry Worker / Supervisor Agrícola' },
  { value: '452011', label: 'Agricultural Inspector / Inspector Agrícola' },
  { value: '452021', label: 'Animal Breeder / Criador de Animales' },
  { value: '452041', label: 'Grader and Sorter, Agricultural Product / Clasificador Agrícola' },
  { value: '452090', label: 'Miscellaneous Agricultural Worker / Otro Trabajador Agrícola' },
  { value: '453031', label: 'Fishing and Hunting Worker / Pescador y Cazador' },
  { value: '454011', label: 'Forest and Conservation Worker / Trabajador Forestal' },
  { value: '454020', label: 'Logging Worker / Talador' },
  // ── Construcción y Extracción ──
  { value: '471011', label: 'First-Line Supervisor of Construction Trades / Supervisor de Construcción' },
  { value: '472011', label: 'Boilermaker / Calderero' },
  { value: '472020', label: 'Brickmason, Blockmason, and Stonemason / Albañil' },
  { value: '472031', label: 'Carpenter / Carpintero' },
  { value: '472040', label: 'Carpet, Floor, and Tile Installer and Finisher / Instalador de Pisos' },
  { value: '472050', label: 'Cement Mason, Concrete Finisher / Albañil de Concreto' },
  { value: '472061', label: 'Construction Laborer / Trabajador de Construcción' },
  { value: '472070', label: 'Construction Equipment Operator / Operador de Equipo de Construcción' },
  { value: '472080', label: 'Drywall Installer, Ceiling Tile Installer, and Taper / Instalador de Pladur' },
  { value: '472111', label: 'Electrician / Electricista' },
  { value: '472121', label: 'Glazier / Vidriero' },
  { value: '472130', label: 'Insulation Worker / Instalador de Aislamiento' },
  { value: '472140', label: 'Painter and Paperhanger / Pintor' },
  { value: '472151', label: 'Pipelayer / Tubero' },
  { value: '472152', label: 'Plumber, Pipefitter, and Steamfitter / Plomero' },
  { value: '472161', label: 'Plasterer and Stucco Mason / Enlucidor' },
  { value: '472171', label: 'Reinforcing Iron and Rebar Worker / Trabajador de Acero de Refuerzo' },
  { value: '472181', label: 'Roofer / Techador' },
  { value: '472211', label: 'Sheet Metal Worker / Trabajador de Lámina' },
  { value: '472221', label: 'Structural Iron and Steel Worker / Trabajador de Estructuras Metálicas' },
  { value: '472231', label: 'Solar Photovoltaic Installer / Instalador Solar' },
  { value: '473010', label: 'Helper, Construction Trade / Ayudante de Construcción' },
  { value: '474011', label: 'Construction and Building Inspector / Inspector de Construcción' },
  { value: '474021', label: 'Elevator and Escalator Installer and Repairer / Instalador de Elevadores' },
  { value: '474031', label: 'Fence Erector / Constructor de Cercas' },
  { value: '474041', label: 'Hazardous Materials Removal Worker / Remoción de Materiales Peligrosos' },
  { value: '474051', label: 'Highway Maintenance Worker / Mantenimiento de Carreteras' },
  { value: '474061', label: 'Rail-Track Laying and Maintenance Equipment Operator / Operador de Vías' },
  { value: '474071', label: 'Septic Tank Servicer and Sewer Pipe Cleaner / Servicio de Fosas Sépticas' },
  { value: '474090', label: 'Miscellaneous Construction and Related Worker / Otro de Construcción' },
  { value: '475010', label: 'Derrick, Rotary Drill, and Service Unit Operator / Operador de Taladro' },
  { value: '475022', label: 'Excavating and Loading Machine Operator / Operador de Excavadora' },
  { value: '475023', label: 'Earth Driller, except Oil and Gas / Perforador de Tierra' },
  { value: '475032', label: 'Explosives Worker / Artificiero' },
  { value: '475040', label: 'Underground Mining Machine Operator / Operador de Maquinaria Minera' },
  { value: '475071', label: 'Roustabout, Oil and Gas / Peón Petrolero' },
  { value: '4750XX', label: 'Other Extraction Worker / Otro Trabajador de Extracción' },
  // ── Instalación, Mantenimiento y Reparación ──
  { value: '491011', label: 'First-Line Supervisor of Mechanics, Installers, and Repairers / Supervisor de Mecánicos' },
  { value: '492011', label: 'Computer, Automated Teller, and Office Machine Repairer / Reparador de Equipos' },
  { value: '492020', label: 'Radio and Telecommunications Equipment Installer and Repairer / Instalador de Telecomunicaciones' },
  { value: '492091', label: 'Avionics Technician / Técnico de Aviónica' },
  { value: '492092', label: 'Electric Motor, Power Tool, and Related Repairer / Reparador Eléctrico' },
  { value: '492093', label: 'Electrical and Electronics Installer, Transportation Equipment / Instalador Eléctrico' },
  { value: '492096', label: 'Electronic Equipment Installer, Motor Vehicles / Instalador Electrónico Automotriz' },
  { value: '492097', label: 'Audiovisual Equipment Installer and Repairer / Instalador Audiovisual' },
  { value: '492098', label: 'Security and Fire Alarm Systems Installer / Instalador de Alarmas' },
  { value: '49209X', label: 'Electrical and Electronics Repairer, Industrial / Reparador Eléctrico Industrial' },
  { value: '493011', label: 'Aircraft Mechanic and Service Technician / Mecánico Aeronáutico' },
  { value: '493021', label: 'Automotive Body and Related Repairer / Hojalatero' },
  { value: '493022', label: 'Automotive Glass Installer and Repairer / Instalador de Vidrios Automotrices' },
  { value: '493023', label: 'Automotive Service Technician and Mechanic / Mecánico Automotriz' },
  { value: '493031', label: 'Bus and Truck Mechanic / Mecánico de Camiones' },
  { value: '493040', label: 'Heavy Vehicle and Mobile Equipment Service Technician / Mecánico de Vehículos Pesados' },
  { value: '493050', label: 'Small Engine Mechanic / Mecánico de Motores Pequeños' },
  { value: '493090', label: 'Miscellaneous Vehicle and Mobile Equipment Mechanic / Otro Mecánico' },
  { value: '499010', label: 'Control and Valve Installer and Repairer / Reparador de Válvulas' },
  { value: '499021', label: 'Heating, Air Conditioning, and Refrigeration Mechanic / Técnico de Climatización' },
  { value: '499031', label: 'Home Appliance Repairer / Reparador de Electrodomésticos' },
  { value: '499043', label: 'Maintenance Worker, Machinery / Mantenimiento de Maquinaria' },
  { value: '499044', label: 'Millwright / Ajustador Industrial' },
  { value: '499051', label: 'Electrical Power-Line Installer and Repairer / Instalador de Líneas Eléctricas' },
  { value: '499052', label: 'Telecommunications Line Installer and Repairer / Instalador de Líneas Telefónicas' },
  { value: '499060', label: 'Precision Instrument and Equipment Repairer / Reparador de Instrumentos' },
  { value: '499071', label: 'Maintenance and Repair Worker, General / Mantenimiento General' },
  { value: '499081', label: 'Wind Turbine Service Technician / Técnico de Turbinas Eólicas' },
  { value: '499091', label: 'Coin, Vending, and Amusement Machine Servicer / Técnico de Máquinas Expendedoras' },
  { value: '499092', label: 'Commercial Diver / Buzo Comercial' },
  { value: '499094', label: 'Locksmith and Safe Repairer / Cerrajero' },
  { value: '499095', label: 'Manufactured Building and Mobile Home Installer / Instalador de Casas Prefabricadas' },
  { value: '499096', label: 'Rigger / Aparejador' },
  { value: '499098', label: 'Helper--Installation, Maintenance, and Repair Worker / Ayudante de Mantenimiento' },
  { value: '49904X', label: 'Industrial and Refractory Machinery Mechanic / Mecánico de Maquinaria Industrial' },
  { value: '49909X', label: 'Other Installation, Maintenance, and Repair Worker / Otro de Mantenimiento' },
  // ── Producción ──
  { value: '511011', label: 'First-Line Supervisor of Production and Operating Worker / Supervisor de Producción' },
  { value: '512011', label: 'Aircraft Structure, Surfaces, Rigging Assembler / Ensamblador Aeronáutico' },
  { value: '512020', label: 'Electrical, Electronics, and Electromechanical Assembler / Ensamblador Electrónico' },
  { value: '512031', label: 'Engine and Other Machine Assembler / Ensamblador de Motores' },
  { value: '512041', label: 'Structural Metal Fabricator and Fitter / Fabricante de Estructuras Metálicas' },
  { value: '5120XX', label: 'Other Assembler and Fabricator / Otro Ensamblador' },
  { value: '513011', label: 'Baker / Panadero' },
  { value: '513020', label: 'Butcher and Other Meat, Poultry, and Fish Processing Worker / Carnicero' },
  { value: '513091', label: 'Food and Tobacco Roasting, Baking, and Drying Machine Operator / Operador de Alimentos' },
  { value: '513092', label: 'Food Batchmaker / Procesador de Alimentos por Lotes' },
  { value: '513093', label: 'Food Cooking Machine Operator and Tender / Operador de Máquinas de Cocina' },
  { value: '513099', label: 'Food Processing Worker, Other / Otro Procesador de Alimentos' },
  { value: '514020', label: 'Forming Machine Setter, Operator (Metal and Plastic) / Operador de Formado' },
  { value: '514031', label: 'Cutting, Punching, and Press Machine Setter (Metal and Plastic) / Operador de Corte' },
  { value: '514033', label: 'Grinding, Lapping, Polishing Machine Tool Setter (Metal and Plastic) / Rectificador' },
  { value: '514041', label: 'Machinist / Maquinista' },
  { value: '514050', label: 'Metal Furnace Operator, Tender, Pourer, and Caster / Operador de Fundición' },
  { value: '514060', label: 'Model Maker and Patternmaker (Metal and Plastic) / Modelista' },
  { value: '514070', label: 'Molder and Molding Machine Setter (Metal and Plastic) / Moldeador' },
  { value: '514111', label: 'Tool and Die Maker / Fabricante de Herramientas' },
  { value: '514120', label: 'Welding, Soldering, and Brazing Worker / Soldador' },
  { value: '51403X', label: 'Other Machine Tool Setter (Metal and Plastic) / Otro Operador de Máquinas' },
  { value: '514XXX', label: 'Other Metal Worker and Plastic Worker / Otro Trabajador de Metal y Plástico' },
  { value: '515111', label: 'Prepress Technician and Worker / Técnico Preprensa' },
  { value: '515112', label: 'Printing Press Operator / Operador de Imprenta' },
  { value: '515113', label: 'Print Binding and Finishing Worker / Encuadernador' },
  { value: '516011', label: 'Laundry and Dry-Cleaning Worker / Lavandero' },
  { value: '516021', label: 'Presser, Textile, Garment / Planchador Textil' },
  { value: '516031', label: 'Sewing Machine Operator / Operador de Máquina de Coser' },
  { value: '516040', label: 'Shoe and Leather Worker / Zapatero' },
  { value: '516050', label: 'Tailor, Dressmaker, and Sewer / Sastre' },
  { value: '516060', label: 'Textile Machine Setter, Operator, and Tender / Operador de Máquinas Textiles' },
  { value: '516093', label: 'Upholsterer / Tapicero' },
  { value: '51609X', label: 'Other Textile, Apparel, and Furnishings Worker / Otro Textil' },
  { value: '517011', label: 'Cabinetmaker and Bench Carpenter / Ebanista' },
  { value: '517021', label: 'Furniture Finisher / Acabador de Muebles' },
  { value: '517041', label: 'Sawing Machine Setter, Operator (Wood) / Operador de Sierra' },
  { value: '517042', label: 'Woodworking Machine Setter, Operator (except Sawing) / Operador de Madera' },
  { value: '5170XX', label: 'Other Woodworker / Otro Trabajador de Madera' },
  { value: '518010', label: 'Power Plant Operator, Distributor, and Dispatcher / Operador de Planta Eléctrica' },
  { value: '518021', label: 'Stationary Engineer and Boiler Operator / Operador de Caldera' },
  { value: '518031', label: 'Water and Wastewater Treatment Plant Operator / Operador de Planta de Agua' },
  { value: '518090', label: 'Miscellaneous Plant and System Operator / Otro Operador de Planta' },
  { value: '519010', label: 'Chemical Processing Machine Setter, Operator / Operador de Procesos Químicos' },
  { value: '519020', label: 'Crushing, Grinding, Polishing, Mixing, and Blending Worker / Operador de Triturado' },
  { value: '519030', label: 'Cutting Worker / Cortador' },
  { value: '519041', label: 'Extruding, Forming, Pressing, and Compacting Machine Operator / Operador de Extrusión' },
  { value: '519051', label: 'Furnace, Kiln, Oven, Drier, and Kettle Operator / Operador de Horno' },
  { value: '519061', label: 'Inspector, Tester, Sorter, Sampler, and Weigher / Inspector y Probador' },
  { value: '519071', label: 'Jeweler and Precious Stone and Metal Worker / Joyero' },
  { value: '519080', label: 'Dental and Ophthalmic Lab Technician / Técnico Dental y Óptico' },
  { value: '519111', label: 'Packaging and Filling Machine Operator and Tender / Operador de Empaque' },
  { value: '519120', label: 'Painting Worker / Operador de Pintura' },
  { value: '519151', label: 'Photographic Process Worker / Procesador Fotográfico' },
  { value: '519160', label: 'Computer Numerically Controlled Tool Operator / Operador CNC' },
  { value: '519191', label: 'Adhesive Bonding Machine Operator and Tender / Operador de Adhesivos' },
  { value: '519194', label: 'Etcher and Engraver / Grabador' },
  { value: '519195', label: 'Molder, Shaper, and Caster (except Metal and Plastic) / Moldeador (no metal)' },
  { value: '519196', label: 'Paper Goods Machine Setter, Operator, and Tender / Operador de Papel' },
  { value: '519197', label: 'Tire Builder / Constructor de Llantas' },
  { value: '519198', label: 'Helper--Production Worker / Ayudante de Producción' },
  { value: '51919X', label: 'Other Production Equipment Operator and Tender / Otro Operador de Producción' },
  { value: '5191XX', label: 'Other Production Worker / Otro Trabajador de Producción' },
  // ── Transporte y Material ──
  { value: '531000', label: 'Supervisor of Transportation and Material Moving Worker / Supervisor de Transporte' },
  { value: '532010', label: 'Aircraft Pilot and Flight Engineer / Piloto de Aeronaves' },
  { value: '532020', label: 'Air Traffic Controller / Controlador de Tráfico Aéreo' },
  { value: '532031', label: 'Flight Attendant / Auxiliar de Vuelo' },
  { value: '533011', label: 'Ambulance Driver / Conductor de Ambulancia' },
  { value: '533030', label: 'Driver/Sales Worker and Truck Driver / Conductor y Repartidor' },
  { value: '533051', label: 'School Bus Driver / Conductor de Autobús Escolar' },
  { value: '533052', label: 'Transit and Intercity Bus Driver / Conductor de Autobús' },
  { value: '533053', label: 'Shuttle Driver and Chauffeur / Chofer' },
  { value: '533054', label: 'Taxi Driver / Taxista' },
  { value: '533099', label: 'Motor Vehicle Operator, Other / Otro Conductor' },
  { value: '534010', label: 'Locomotive Engineer and Operator / Maquinista Ferroviario' },
  { value: '534031', label: 'Railroad Conductor and Yardmaster / Conductor Ferroviario' },
  { value: '535011', label: 'Sailor and Marine Oiler / Marinero' },
  { value: '535020', label: 'Ship and Boat Captain and Operator / Capitán de Barco' },
  { value: '535031', label: 'Ship Engineer / Ingeniero Naval' },
  { value: '536021', label: 'Parking Attendant / Valet' },
  { value: '536030', label: 'Transportation Service Attendant / Asistente de Transporte' },
  { value: '536051', label: 'Transportation Inspector / Inspector de Transporte' },
  { value: '536061', label: 'Passenger Attendant / Asistente de Pasajeros' },
  { value: '5340XX', label: 'Other Rail Transportation Worker / Otro Trabajador Ferroviario' },
  { value: '5360XX', label: 'Other Transportation Worker / Otro de Transporte' },
  { value: '537021', label: 'Crane and Tower Operator / Operador de Grúa' },
  { value: '537051', label: 'Industrial Truck and Tractor Operator / Operador de Montacargas' },
  { value: '537061', label: 'Cleaner of Vehicles and Equipment / Limpiador de Vehículos' },
  { value: '537062', label: 'Laborer and Freight, Stock, and Material Mover / Cargador' },
  { value: '537063', label: 'Machine Feeder and Offbearer / Alimentador de Máquinas' },
  { value: '537064', label: 'Packer and Packager, Hand / Empacador' },
  { value: '537065', label: 'Stocker and Order Filler / Almacenista' },
  { value: '537070', label: 'Pumping Station Operator / Operador de Estación de Bombeo' },
  { value: '537081', label: 'Refuse and Recyclable Material Collector / Recolector de Basura' },
  { value: '5370XX', label: 'Conveyor, Dredge, and Hoist and Winch Operator / Operador de Transportador' },
  { value: '5371XX', label: 'Other Material Moving Worker / Otro Trabajador de Carga' },
  // ── Militar ──
  { value: '551010', label: 'Military Officer Special and Tactical Operations Leader / Oficial Militar' },
  { value: '552010', label: 'First-Line Enlisted Military Supervisor / Supervisor Militar' },
  { value: '553010', label: 'Military Enlisted Tactical Operations Specialist / Especialista Militar Táctico' },
  { value: '554010', label: 'Military, Rank Not Specified / Militar, Rango No Especificado' },
  // ── Especial ──
  { value: '999999', label: 'Unemployed or Never Worked / Desempleado o Sin Experiencia Laboral' },
] as const

export type OccupationCode = typeof OCCUPATION_OPTIONS[number]['value']
export const OCCUPATION_VALUES = OCCUPATION_OPTIONS.map(o => o.value) as unknown as readonly [string, ...string[]]

// ─── High-risk activities — Business (P1) ────────────────────────────────────
// Valores exactos del enum Bridge OpenAPI spec
export const HIGH_RISK_ACTIVITIES = [
  { value: 'adult_entertainment',                                          label: 'Entretenimiento para adultos' },
  { value: 'gambling',                                                     label: 'Apuestas / Juegos de azar' },
  { value: 'hold_client_funds',                                            label: 'Custodia de fondos de clientes' },
  { value: 'investment_services',                                          label: 'Servicios de inversión' },
  { value: 'lending_banking',                                              label: 'Préstamos y banca' },
  { value: 'marijuana_or_related_services',                                label: 'Cannabis / Marihuana' },
  { value: 'money_services',                                               label: 'Servicios de dinero (MSB)' },
  { value: 'nicotine_tobacco_or_related_services',                         label: 'Tabaco / Nicotina' },
  { value: 'operate_foreign_exchange_virtual_currencies_brokerage_otc',    label: 'Exchange / OTC de divisas o criptomonedas' },
  { value: 'pharmaceuticals',                                              label: 'Farmacéutica / Medicamentos' },
  { value: 'precious_metals_precious_stones_jewelry',                      label: 'Metales preciosos / Joyería' },
  { value: 'safe_deposit_box_rentals',                                     label: 'Alquiler de cajas de seguridad' },
  { value: 'third_party_payment_processing',                               label: 'Procesamiento de pagos de terceros' },
  { value: 'weapons_firearms_and_explosives',                              label: 'Armas de fuego y explosivos' },
  { value: 'none_of_the_above',                                            label: 'Ninguna de las anteriores' },
] as const

export type HighRiskActivity = typeof HIGH_RISK_ACTIVITIES[number]['value']

// ─── Business industries — NAICS 2022 codes (selección resumida más relevantes) ──
// Ref: https://apidocs.bridge.xyz/platform/customers/compliance/business-industry-list-updated-2022-naics-codes
export const BUSINESS_INDUSTRIES = [
  { value: '111150',  label: 'Agricultura — Cultivo de granos' },
  { value: '212311',  label: 'Minería y Canteras' },
  { value: '221112',  label: 'Generación eléctrica (combustible fósil)' },
  { value: '221114',  label: 'Generación de energía solar' },
  { value: '311111',  label: 'Manufactura de alimentos' },
  { value: '322110',  label: 'Manufactura de papel / celulosa' },
  { value: '324110',  label: 'Refinerías de petróleo' },
  { value: '334111',  label: 'Manufactura de computadoras / electrónica' },
  { value: '334210',  label: 'Equipos de telecomunicaciones' },
  { value: '423110',  label: 'Comercio mayorista — Automotriz' },
  { value: '441110',  label: 'Concesionarios de autos' },
  { value: '444110',  label: 'Tiendas de materiales de construcción' },
  { value: '445110',  label: 'Supermercados / Grocery' },
  { value: '449110',  label: 'Muebles y mobiliario' },
  { value: '455110',  label: 'Tiendas departamentales' },
  { value: '484110',  label: 'Transporte de carga (local)' },
  { value: '484121',  label: 'Transporte de carga (larga distancia)' },
  { value: '491110',  label: 'Servicio postal / courier' },
  { value: '511210',  label: 'Editores de software' },
  { value: '517111',  label: 'Telecomunicaciones (línea fija)' },
  { value: '517112',  label: 'Telecomunicaciones (inalámbrica)' },
  { value: '518210',  label: 'Procesamiento de datos / hosting / cloud' },
  { value: '519290',  label: 'Servicios de información / portales web' },
  { value: '521110',  label: 'Banca central' },
  { value: '522110',  label: 'Banca comercial' },
  { value: '522130',  label: 'Cooperativas de ahorro y crédito' },
  { value: '522210',  label: 'Emisión de tarjetas de crédito' },
  { value: '522291',  label: 'Crédito al consumo / préstamos' },
  { value: '522320',  label: 'Procesamiento de pagos (fintech)' },
  { value: '523150',  label: 'Banca de inversión y valores' },
  { value: '523910',  label: 'Intermediación financiera' },
  { value: '523940',  label: 'Gestión de portafolio / asesoría financiera' },
  { value: '524210',  label: 'Seguros' },
  { value: '531110',  label: 'Alquiler de bienes inmuebles' },
  { value: '531210',  label: 'Corretaje de bienes inmuebles' },
  { value: '541110',  label: 'Servicios legales / abogados' },
  { value: '541211',  label: 'Contabilidad / auditoría' },
  { value: '541511',  label: 'Programación / desarrollo de software' },
  { value: '541512',  label: 'Diseño de sistemas informáticos' },
  { value: '541611',  label: 'Consultoría de negocios' },
  { value: '541613',  label: 'Consultoría de marketing' },
  { value: '541810',  label: 'Agencias de publicidad' },
  { value: '561311',  label: 'Agencias de empleo' },
  { value: '561510',  label: 'Agencias de viajes' },
  { value: '561790',  label: 'Servicios de jardinería / paisajismo' },
  { value: '611110',  label: 'Educación primaria / secundaria' },
  { value: '611310',  label: 'Educación universitaria' },
  { value: '621111',  label: 'Consultorios médicos' },
  { value: '621210',  label: 'Consultorios dentales' },
  { value: '622110',  label: 'Hospitales generales' },
  { value: '711190',  label: 'Artes escénicas / espectáculos' },
  { value: '713940',  label: 'Gimnasios y centros deportivos' },
  { value: '721110',  label: 'Hoteles y resorts' },
  { value: '722511',  label: 'Restaurantes (servicio completo)' },
  { value: '722513',  label: 'Restaurantes (rápido)' },
  { value: '811111',  label: 'Reparación automotriz general' },
  { value: '812111',  label: 'Peluquerías / barberías' },
  { value: '812210',  label: 'Funerarias / servicios fúnebres' },
  { value: '812310',  label: 'Lavanderías / tintorerías' },
  { value: '813110',  label: 'Organizaciones religiosas' },
  { value: '813211',  label: 'ONGs / fundaciones caritativas' },
  { value: '926110',  label: 'Administración pública / programas económicos' },
] as const

export type BusinessIndustryCode = typeof BUSINESS_INDUSTRIES[number]['value']
export const BUSINESS_INDUSTRY_VALUES = BUSINESS_INDUSTRIES.map(i => i.value) as unknown as readonly [string, ...string[]]

// ─── Business types ───────────────────────────────────────────────────────────
export const BUSINESS_TYPES = [
  { value: 'corporation', label: 'Sociedad Anónima (S.A. / Corporation)' },
  { value: 'llc',         label: 'Sociedad de Responsabilidad Limitada (S.R.L. / LLC)' },
  { value: 'partnership', label: 'Sociedad Colectiva / Partnership' },
  { value: 'sole_prop',   label: 'Empresa Unipersonal / Sole Proprietorship' },
  { value: 'cooperative', label: 'Cooperativa' },
  { value: 'trust',       label: 'Fideicomiso / Trust' },
  { value: 'other',       label: 'Otro' },
] as const

export type BusinessType = typeof BUSINESS_TYPES[number]['value']

// ─── Source of funds — Business ───────────────────────────────────────────────
export const BUSINESS_SOURCE_OF_FUNDS = [
  { value: 'sales_of_goods_and_services', label: 'Ventas de bienes y servicios' },
  { value: 'owners_capital',             label: 'Capital de los socios' },
  { value: 'investment_proceeds',        label: 'Rendimientos de inversiones' },
  { value: 'business_loans',            label: 'Préstamos empresariales' },
  { value: 'grants',                    label: 'Subvenciones / Donaciones' },
  { value: 'inter_company_funds',       label: 'Fondos intercompañía' },
  { value: 'sale_of_assets',            label: 'Venta de activos' },
  { value: 'treasury_reserves',         label: 'Reservas de tesorería' },
  { value: 'legal_settlement',          label: 'Acuerdo legal' },
  { value: 'pension_retirement',        label: 'Pensión / Fondo de retiro' },
  { value: 'third_party_funds',         label: 'Fondos de terceros' },
] as const

export type BusinessSourceOfFunds = typeof BUSINESS_SOURCE_OF_FUNDS[number]['value']

// ─── Account purpose — Business ───────────────────────────────────────────────
export const BUSINESS_ACCOUNT_PURPOSE = [
  { value: 'purchase_goods_and_services',             label: 'Compra de bienes y servicios' },
  { value: 'receive_payments_for_goods_and_services', label: 'Cobros por bienes/servicios' },
  { value: 'payroll',                                 label: 'Pago de nómina' },
  { value: 'treasury_management',                    label: 'Gestión de tesorería' },
  { value: 'investment_purposes',                    label: 'Inversiones' },
  { value: 'payments_to_friends_or_family_abroad',   label: 'Pagos internacionales' },
  { value: 'protect_wealth',                         label: 'Protección de patrimonio' },
  { value: 'ecommerce_retail_payments',              label: 'Pagos e-commerce / retail' },
  { value: 'charitable_donations',                   label: 'Donaciones benéficas' },
  // FIX D-02: missing value added to match Bridge spec (13 values total)
  { value: 'personal_or_living_expenses',            label: 'Gastos personales / manutención' },
  { value: 'tax_optimization',                       label: 'Optimización fiscal' },
  { value: 'third_party_money_transmission',         label: 'Transmisión de fondos de terceros' },
  { value: 'other',                                  label: 'Otro' },
] as const

export type BusinessAccountPurpose = typeof BUSINESS_ACCOUNT_PURPOSE[number]['value']

// ─── Countries — ISO 3166-1 alpha-3 (países habilitados por Bridge) ──────────
export const BRIDGE_COUNTRIES = [
  { value: 'ARG', label: 'Argentina' },
  { value: 'BOL', label: 'Bolivia' },
  { value: 'BRA', label: 'Brasil' },
  { value: 'CHL', label: 'Chile' },
  { value: 'COL', label: 'Colombia' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'DOM', label: 'Rep. Dominicana' },
  { value: 'ECU', label: 'Ecuador' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'GUY', label: 'Guyana' },
  { value: 'HND', label: 'Honduras' },
  { value: 'MEX', label: 'México' },
  { value: 'PAN', label: 'Panamá' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'PER', label: 'Perú' },
  { value: 'SUR', label: 'Suriname' },
  { value: 'URY', label: 'Uruguay' },
] as const

export type BridgeCountryCode = typeof BRIDGE_COUNTRIES[number]['value']

// ─── Subdivisions — ISO 3166-2 (código sin prefijo de país, ej. "L" no "BO-L") ─
export const COUNTRY_SUBDIVISIONS: Record<string, { value: string; label: string }[]> = {
  BOL: [
    { value: 'B', label: 'El Beni' },
    { value: 'C', label: 'Cochabamba' },
    { value: 'H', label: 'Chuquisaca' },
    { value: 'L', label: 'La Paz' },
    { value: 'N', label: 'Pando' },
    { value: 'O', label: 'Oruro' },
    { value: 'P', label: 'Potosí' },
    { value: 'S', label: 'Santa Cruz' },
    { value: 'T', label: 'Tarija' },
  ],
  ARG: [
    { value: 'C', label: 'Ciudad Autónoma de Buenos Aires' },
    { value: 'B', label: 'Buenos Aires' },
    { value: 'K', label: 'Catamarca' },
    { value: 'H', label: 'Chaco' },
    { value: 'U', label: 'Chubut' },
    { value: 'X', label: 'Córdoba' },
    { value: 'W', label: 'Corrientes' },
    { value: 'E', label: 'Entre Ríos' },
    { value: 'P', label: 'Formosa' },
    { value: 'Y', label: 'Jujuy' },
    { value: 'L', label: 'La Pampa' },
    { value: 'F', label: 'La Rioja' },
    { value: 'M', label: 'Mendoza' },
    { value: 'N', label: 'Misiones' },
    { value: 'Q', label: 'Neuquén' },
    { value: 'R', label: 'Río Negro' },
    { value: 'A', label: 'Salta' },
    { value: 'J', label: 'San Juan' },
    { value: 'D', label: 'San Luis' },
    { value: 'Z', label: 'Santa Cruz' },
    { value: 'S', label: 'Santa Fe' },
    { value: 'G', label: 'Santiago del Estero' },
    { value: 'V', label: 'Tierra del Fuego' },
    { value: 'T', label: 'Tucumán' },
  ],

  BRA: [
    { value: 'AC', label: 'Acre' },
    { value: 'AL', label: 'Alagoas' },
    { value: 'AP', label: 'Amapá' },
    { value: 'AM', label: 'Amazonas' },
    { value: 'BA', label: 'Bahia' },
    { value: 'CE', label: 'Ceará' },
    { value: 'DF', label: 'Distrito Federal' },
    { value: 'ES', label: 'Espírito Santo' },
    { value: 'GO', label: 'Goiás' },
    { value: 'MA', label: 'Maranhão' },
    { value: 'MT', label: 'Mato Grosso' },
    { value: 'MS', label: 'Mato Grosso do Sul' },
    { value: 'MG', label: 'Minas Gerais' },
    { value: 'PA', label: 'Pará' },
    { value: 'PB', label: 'Paraíba' },
    { value: 'PR', label: 'Paraná' },
    { value: 'PE', label: 'Pernambuco' },
    { value: 'PI', label: 'Piauí' },
    { value: 'RJ', label: 'Rio de Janeiro' },
    { value: 'RN', label: 'Rio Grande do Norte' },
    { value: 'RS', label: 'Rio Grande do Sul' },
    { value: 'RO', label: 'Rondônia' },
    { value: 'RR', label: 'Roraima' },
    { value: 'SC', label: 'Santa Catarina' },
    { value: 'SP', label: 'São Paulo' },
    { value: 'SE', label: 'Sergipe' },
    { value: 'TO', label: 'Tocantins' },
  ],
  CHL: [
    { value: 'AI', label: 'Aysén' },
    { value: 'AN', label: 'Antofagasta' },
    { value: 'AP', label: 'Arica y Parinacota' },
    { value: 'AR', label: 'La Araucanía' },
    { value: 'AT', label: 'Atacama' },
    { value: 'BI', label: 'Biobío' },
    { value: 'CO', label: 'Coquimbo' },
    { value: 'LI', label: 'Libertador Gral. Bernardo O\'Higgins' },
    { value: 'LL', label: 'Los Lagos' },
    { value: 'LR', label: 'Los Ríos' },
    { value: 'MA', label: 'Magallanes' },
    { value: 'ML', label: 'Maule' },
    { value: 'NB', label: 'Ñuble' },
    { value: 'RM', label: 'Región Metropolitana' },
    { value: 'TA', label: 'Tarapacá' },
    { value: 'VS', label: 'Valparaíso' },
  ],
  COL: [
    { value: 'AMA', label: 'Amazonas' },
    { value: 'ANT', label: 'Antioquia' },
    { value: 'ARA', label: 'Arauca' },
    { value: 'ATL', label: 'Atlántico' },
    { value: 'BOL', label: 'Bolívar' },
    { value: 'BOY', label: 'Boyacá' },
    { value: 'CAL', label: 'Caldas' },
    { value: 'CAQ', label: 'Caquetá' },
    { value: 'CAS', label: 'Casanare' },
    { value: 'CAU', label: 'Cauca' },
    { value: 'CES', label: 'Cesar' },
    { value: 'CHO', label: 'Chocó' },
    { value: 'COR', label: 'Córdoba' },
    { value: 'CUN', label: 'Cundinamarca' },
    { value: 'DC', label: 'Bogotá D.C.' },
    { value: 'GUA', label: 'Guainía' },
    { value: 'GUV', label: 'Guaviare' },
    { value: 'HUI', label: 'Huila' },
    { value: 'LAG', label: 'La Guajira' },
    { value: 'MAG', label: 'Magdalena' },
    { value: 'MET', label: 'Meta' },
    { value: 'NAR', label: 'Nariño' },
    { value: 'NSA', label: 'Norte de Santander' },
    { value: 'PUT', label: 'Putumayo' },
    { value: 'QUI', label: 'Quindío' },
    { value: 'RIS', label: 'Risaralda' },
    { value: 'SAN', label: 'Santander' },
    { value: 'SAP', label: 'San Andrés y Providencia' },
    { value: 'SUC', label: 'Sucre' },
    { value: 'TOL', label: 'Tolima' },
    { value: 'VAC', label: 'Valle del Cauca' },
    { value: 'VID', label: 'Vichada' },
  ],
  CRI: [
    { value: 'A', label: 'Alajuela' },
    { value: 'C', label: 'Cartago' },
    { value: 'G', label: 'Guanacaste' },
    { value: 'H', label: 'Heredia' },
    { value: 'L', label: 'Limón' },
    { value: 'P', label: 'Puntarenas' },
    { value: 'SJ', label: 'San José' },
  ],
  DOM: [
    { value: '01', label: 'Distrito Nacional' },
    { value: '02', label: 'Azua' },
    { value: '03', label: 'Bahoruco' },
    { value: '04', label: 'Barahona' },
    { value: '05', label: 'Dajabón' },
    { value: '06', label: 'Duarte' },
    { value: '07', label: 'Elías Piña' },
    { value: '08', label: 'El Seibo' },
    { value: '09', label: 'Espaillat' },
    { value: '10', label: 'Independencia' },
    { value: '11', label: 'La Altagracia' },
    { value: '12', label: 'La Romana' },
    { value: '13', label: 'La Vega' },
    { value: '14', label: 'María Trinidad Sánchez' },
    { value: '15', label: 'Monte Cristi' },
    { value: '16', label: 'Pedernales' },
    { value: '17', label: 'Peravia' },
    { value: '18', label: 'Puerto Plata' },
    { value: '19', label: 'Hermanas Mirabal' },
    { value: '20', label: 'Samaná' },
    { value: '21', label: 'San Cristóbal' },
    { value: '22', label: 'San Juan' },
    { value: '23', label: 'San Pedro de Macorís' },
    { value: '24', label: 'Sánchez Ramírez' },
    { value: '25', label: 'Santiago' },
    { value: '26', label: 'Santiago Rodríguez' },
    { value: '27', label: 'Valverde' },
    { value: '28', label: 'Monseñor Nouel' },
    { value: '29', label: 'Monte Plata' },
    { value: '30', label: 'Hato Mayor' },
    { value: '31', label: 'San José de Ocoa' },
    { value: '32', label: 'Santo Domingo' },
  ],
  ECU: [
    { value: 'A', label: 'Azuay' },
    { value: 'B', label: 'Bolívar' },
    { value: 'F', label: 'Cañar' },
    { value: 'C', label: 'Carchi' },
    { value: 'S', label: 'Chimborazo' },
    { value: 'X', label: 'Cotopaxi' },
    { value: 'H', label: 'El Oro' },
    { value: 'E', label: 'Esmeraldas' },
    { value: 'W', label: 'Galápagos' },
    { value: 'G', label: 'Guayas' },
    { value: 'I', label: 'Imbabura' },
    { value: 'L', label: 'Loja' },
    { value: 'R', label: 'Los Ríos' },
    { value: 'M', label: 'Manabí' },
    { value: 'SE', label: 'Morona Santiago' },
    { value: 'Z', label: 'Napo' },
    { value: 'D', label: 'Orellana' },
    { value: 'Y', label: 'Pastaza' },
    { value: 'P', label: 'Pichincha' },
    { value: 'SD', label: 'Santa Elena' },
    { value: 'U', label: 'Santo Domingo de los Tsáchilas' },
    { value: 'N', label: 'Sucumbíos' },
    { value: 'T', label: 'Tungurahua' },
    { value: 'O', label: 'Zamora Chinchipe' },
  ],
  SLV: [
    { value: 'AH', label: 'Ahuachapán' },
    { value: 'CA', label: 'Cabañas' },
    { value: 'CH', label: 'Chalatenango' },
    { value: 'CU', label: 'Cuscatlán' },
    { value: 'LI', label: 'La Libertad' },
    { value: 'PA', label: 'La Paz' },
    { value: 'UN', label: 'La Unión' },
    { value: 'MO', label: 'Morazán' },
    { value: 'SM', label: 'San Miguel' },
    { value: 'SS', label: 'San Salvador' },
    { value: 'SA', label: 'Santa Ana' },
    { value: 'SV', label: 'San Vicente' },
    { value: 'SO', label: 'Sonsonate' },
    { value: 'US', label: 'Usulután' },
  ],
  GTM: [
    { value: 'AV', label: 'Alta Verapaz' },
    { value: 'BV', label: 'Baja Verapaz' },
    { value: 'CM', label: 'Chimaltenango' },
    { value: 'CQ', label: 'Chiquimula' },
    { value: 'PE', label: 'El Petén' },
    { value: 'PR', label: 'El Progreso' },
    { value: 'QC', label: 'El Quiché' },
    { value: 'ES', label: 'Escuintla' },
    { value: 'GU', label: 'Guatemala' },
    { value: 'HU', label: 'Huehuetenango' },
    { value: 'IZ', label: 'Izabal' },
    { value: 'JA', label: 'Jalapa' },
    { value: 'JU', label: 'Jutiapa' },
    { value: 'QZ', label: 'Quetzaltenango' },
    { value: 'RE', label: 'Retalhuleu' },
    { value: 'SA', label: 'Sacatepéquez' },
    { value: 'SM', label: 'San Marcos' },
    { value: 'SO', label: 'Santa Rosa' },
    { value: 'SR', label: 'Sololá' },
    { value: 'SU', label: 'Suchitepéquez' },
    { value: 'TO', label: 'Totonicapán' },
    { value: 'ZA', label: 'Zacapa' },
  ],
  GUY: [
    { value: 'BA', label: 'Barima-Waini' },
    { value: 'CU', label: 'Cuyuni-Mazaruni' },
    { value: 'DE', label: 'Demerara-Mahaica' },
    { value: 'EB', label: 'East Berbice-Corentyne' },
    { value: 'ES', label: 'Essequibo Islands-West Demerara' },
    { value: 'MA', label: 'Mahaica-Berbice' },
    { value: 'PM', label: 'Pomeroon-Supenaam' },
    { value: 'PT', label: 'Potaro-Siparuni' },
    { value: 'UD', label: 'Upper Demerara-Berbice' },
    { value: 'UT', label: 'Upper Takutu-Upper Essequibo' },
  ],
  HND: [
    { value: 'AT', label: 'Atlántida' },
    { value: 'CH', label: 'Choluteca' },
    { value: 'CL', label: 'Colón' },
    { value: 'CM', label: 'Comayagua' },
    { value: 'CP', label: 'Copán' },
    { value: 'CR', label: 'Cortés' },
    { value: 'EP', label: 'El Paraíso' },
    { value: 'FM', label: 'Francisco Morazán' },
    { value: 'GD', label: 'Gracias a Dios' },
    { value: 'IN', label: 'Intibucá' },
    { value: 'IB', label: 'Islas de la Bahía' },
    { value: 'LP', label: 'La Paz' },
    { value: 'LE', label: 'Lempira' },
    { value: 'OC', label: 'Ocotepeque' },
    { value: 'OL', label: 'Olancho' },
    { value: 'SB', label: 'Santa Bárbara' },
    { value: 'VA', label: 'Valle' },
    { value: 'YO', label: 'Yoro' },
  ],
  MEX: [
    { value: 'AGU', label: 'Aguascalientes' },
    { value: 'BCN', label: 'Baja California' },
    { value: 'BCS', label: 'Baja California Sur' },
    { value: 'CAM', label: 'Campeche' },
    { value: 'CHP', label: 'Chiapas' },
    { value: 'CHH', label: 'Chihuahua' },
    { value: 'CMX', label: 'Ciudad de México' },
    { value: 'COA', label: 'Coahuila' },
    { value: 'COL', label: 'Colima' },
    { value: 'DUR', label: 'Durango' },
    { value: 'GUA', label: 'Guanajuato' },
    { value: 'GRO', label: 'Guerrero' },
    { value: 'HID', label: 'Hidalgo' },
    { value: 'JAL', label: 'Jalisco' },
    { value: 'MEX', label: 'Estado de México' },
    { value: 'MIC', label: 'Michoacán' },
    { value: 'MOR', label: 'Morelos' },
    { value: 'NAY', label: 'Nayarit' },
    { value: 'NLE', label: 'Nuevo León' },
    { value: 'OAX', label: 'Oaxaca' },
    { value: 'PUE', label: 'Puebla' },
    { value: 'QUE', label: 'Querétaro' },
    { value: 'ROO', label: 'Quintana Roo' },
    { value: 'SLP', label: 'San Luis Potosí' },
    { value: 'SIN', label: 'Sinaloa' },
    { value: 'SON', label: 'Sonora' },
    { value: 'TAB', label: 'Tabasco' },
    { value: 'TAM', label: 'Tamaulipas' },
    { value: 'TLA', label: 'Tlaxcala' },
    { value: 'VER', label: 'Veracruz' },
    { value: 'YUC', label: 'Yucatán' },
    { value: 'ZAC', label: 'Zacatecas' },
  ],
  PAN: [
    { value: '1', label: 'Bocas del Toro' },
    { value: '4', label: 'Chiriquí' },
    { value: '2', label: 'Coclé' },
    { value: '3', label: 'Colón' },
    { value: '5', label: 'Darién' },
    { value: '6', label: 'Herrera' },
    { value: '7', label: 'Los Santos' },
    { value: '8', label: 'Panamá' },
    { value: '10', label: 'Panamá Oeste' },
    { value: '9', label: 'Veraguas' },
    { value: 'EM', label: 'Emberá' },
    { value: 'KY', label: 'Guna Yala' },
    { value: 'NB', label: 'Ngäbe-Buglé' },
  ],
  PRY: [
    { value: 'ASU', label: 'Asunción' },
    { value: '10', label: 'Alto Paraná' },
    { value: '16', label: 'Alto Paraguay' },
    { value: '13', label: 'Amambay' },
    { value: '17', label: 'Boquerón' },
    { value: '5', label: 'Caaguazú' },
    { value: '6', label: 'Caazapá' },
    { value: '14', label: 'Canindeyú' },
    { value: '11', label: 'Central' },
    { value: '1', label: 'Concepción' },
    { value: '3', label: 'Cordillera' },
    { value: '4', label: 'Guairá' },
    { value: '7', label: 'Itapúa' },
    { value: '8', label: 'Misiones' },
    { value: '12', label: 'Ñeembucú' },
    { value: '9', label: 'Paraguarí' },
    { value: '15', label: 'Presidente Hayes' },
    { value: '2', label: 'San Pedro' },
  ],
  PER: [
    { value: 'AMA', label: 'Amazonas' },
    { value: 'ANC', label: 'Áncash' },
    { value: 'APU', label: 'Apurímac' },
    { value: 'ARE', label: 'Arequipa' },
    { value: 'AYA', label: 'Ayacucho' },
    { value: 'CAJ', label: 'Cajamarca' },
    { value: 'CAL', label: 'El Callao' },
    { value: 'CUS', label: 'Cusco' },
    { value: 'HUV', label: 'Huancavelica' },
    { value: 'HUC', label: 'Huánuco' },
    { value: 'ICA', label: 'Ica' },
    { value: 'JUN', label: 'Junín' },
    { value: 'LAL', label: 'La Libertad' },
    { value: 'LAM', label: 'Lambayeque' },
    { value: 'LIM', label: 'Lima' },
    { value: 'LOR', label: 'Loreto' },
    { value: 'MDD', label: 'Madre de Dios' },
    { value: 'MOQ', label: 'Moquegua' },
    { value: 'PAS', label: 'Pasco' },
    { value: 'PIU', label: 'Piura' },
    { value: 'PUN', label: 'Puno' },
    { value: 'SAM', label: 'San Martín' },
    { value: 'TAC', label: 'Tacna' },
    { value: 'TUM', label: 'Tumbes' },
    { value: 'UCA', label: 'Ucayali' },
  ],
  SUR: [
    { value: 'BR', label: 'Brokopondo' },
    { value: 'CM', label: 'Commewijne' },
    { value: 'CR', label: 'Coronie' },
    { value: 'MA', label: 'Marowijne' },
    { value: 'NI', label: 'Nickerie' },
    { value: 'PR', label: 'Para' },
    { value: 'PM', label: 'Paramaribo' },
    { value: 'SA', label: 'Saramacca' },
    { value: 'SI', label: 'Sipaliwini' },
    { value: 'WA', label: 'Wanica' },
  ],
  URY: [
    { value: 'AR', label: 'Artigas' },
    { value: 'CA', label: 'Canelones' },
    { value: 'CL', label: 'Cerro Largo' },
    { value: 'CO', label: 'Colonia' },
    { value: 'DU', label: 'Durazno' },
    { value: 'FS', label: 'Flores' },
    { value: 'FD', label: 'Florida' },
    { value: 'LA', label: 'Lavalleja' },
    { value: 'MA', label: 'Maldonado' },
    { value: 'MO', label: 'Montevideo' },
    { value: 'PA', label: 'Paysandú' },
    { value: 'RN', label: 'Río Negro' },
    { value: 'RV', label: 'Rivera' },
    { value: 'RO', label: 'Rocha' },
    { value: 'SA', label: 'Salto' },
    { value: 'SJ', label: 'San José' },
    { value: 'SO', label: 'Soriano' },
    { value: 'TA', label: 'Tacuarembó' },
    { value: 'TT', label: 'Treinta y Tres' },
  ],
}

// ─── Countries with required subdivisions ─────────────────────────────────────
export const COUNTRIES_WITH_SUBDIVISIONS = new Set(Object.keys(COUNTRY_SUBDIVISIONS))

// ─── Helper: extract values only (for zod enum) ──────────────────────────────
export const BRIDGE_COUNTRY_CODES = BRIDGE_COUNTRIES.map(c => c.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_ID_TYPE_VALUES = INDIVIDUAL_ID_TYPES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_SOF_VALUES = INDIVIDUAL_SOURCE_OF_FUNDS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const INDIVIDUAL_PURPOSE_VALUES = INDIVIDUAL_ACCOUNT_PURPOSE.map(t => t.value) as unknown as readonly [string, ...string[]]
export const MONTHLY_PAYMENT_VALUES = EXPECTED_MONTHLY_PAYMENTS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_TYPE_VALUES = BUSINESS_TYPES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_SOF_VALUES = BUSINESS_SOURCE_OF_FUNDS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const BUSINESS_PURPOSE_VALUES = BUSINESS_ACCOUNT_PURPOSE.map(t => t.value) as unknown as readonly [string, ...string[]]
// P1 / New exports
export const EMPLOYMENT_STATUS_VALUES = EMPLOYMENT_STATUS_OPTIONS.map(t => t.value) as unknown as readonly [string, ...string[]]
export const ANNUAL_REVENUE_VALUES = ANNUAL_REVENUE_RANGES.map(t => t.value) as unknown as readonly [string, ...string[]]
export const HIGH_RISK_ACTIVITY_VALUES = HIGH_RISK_ACTIVITIES.map(t => t.value) as unknown as readonly [string, ...string[]]

// ─── Dial codes — ISO 3166-1 alpha-3 → country calling code ─────────────────
export const COUNTRY_DIAL_CODES: Record<string, string> = {
  ARG: '+54',
  BOL: '+591',
  BRA: '+55',
  CHL: '+56',
  COL: '+57',
  CRI: '+506',
  DOM: '+1-809',
  ECU: '+593',
  SLV: '+503',
  GTM: '+502',
  GUY: '+592',
  HND: '+504',
  MEX: '+52',
  PAN: '+507',
  PRY: '+595',
  PER: '+51',
  SUR: '+597',
  URY: '+598',
}
